package com.dgsoft.common.system.model;
// Generated May 7, 2013 11:49:56 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessInstance generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_INSTANCE", catalog = "DG_SYSTEM")
public class BusinessInstance implements java.io.Serializable {

    public enum BusinessState {
        RUNNING, COMPLETE, ABORT, SUSPEND;
    }

    private String id;
    private BusinessDefine businessDefine;
    private Date createTime;
    private Date completeTime;
    private String mark;
    private BusinessState state;
    private Employee employee;
    private String processMessages;

    private Set<BusinessTask> businessTasks = new HashSet<BusinessTask>(0);

    public BusinessInstance() {
        this.state = BusinessState.RUNNING;
        this.createTime = new Date();
    }

    public BusinessInstance(Employee employee) {
        this();
        this.employee = employee;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CURRENT_OPER_EMPLOYEE_ID")
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BUSINESS_DEFINE_ID", nullable = false)
    @NotNull
    public BusinessDefine getBusinessDefine() {
        return this.businessDefine;
    }

    public void setBusinessDefine(BusinessDefine businessDefine) {
        this.businessDefine = businessDefine;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", nullable = false, length = 19, columnDefinition = "DATETIME")
    @NotNull
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COMPLETE_TIME", nullable = true, length = 19, columnDefinition = "DATETIME")
    public Date getCompleteTime() {
        return this.completeTime;
    }

    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    @Column(name = "MARK", length = 200)
    @Size(max = 200)
    public String getMark() {
        return this.mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    @Column(name = "STATE", nullable = false)
    @NotNull
    @Enumerated(EnumType.STRING)
    public BusinessState getState() {
        return this.state;
    }

    public void setState(BusinessState state) {
        this.state = state;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "businessInstance")
    public Set<BusinessTask> getBusinessTasks() {
        return this.businessTasks;
    }

    public void setBusinessTasks(Set<BusinessTask> businessTasks) {
        this.businessTasks = businessTasks;
    }

    @Column(name = "PROCESS_MESSAGE", length = 400)
    @Size(max = 400)
    public String getProcessMessages() {
        return processMessages;
    }

    public void setProcessMessages(String processMessages) {
        this.processMessages = processMessages;
    }
}
