package com.dgsoft.common.system.model;
// Generated Apr 28, 2013 11:02:59 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * FileSubscribe generated by hbm2java
 */
@Entity
@Table(name = "FILE_SUBSCRIBE", catalog = "DG_SYSTEM")
public class FileSubscribe implements java.io.Serializable {

	private String id;
	private BusinessDefine businessDefine;
	private int type;
	private boolean important;
	private String wfTASK;
	private String wfVer;
	private int priority;

	public FileSubscribe() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_DEFINE", nullable = false)
	@NotNull
	public BusinessDefine getBusinessDefine() {
		return this.businessDefine;
	}

	public void setBusinessDefine(BusinessDefine businessDefine) {
		this.businessDefine = businessDefine;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "IMPORTANT", nullable = false)
	public boolean isImportant() {
		return this.important;
	}

	public void setImportant(boolean important) {
		this.important = important;
	}

	@Column(name = "WF_TASK", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getWfTASK() {
		return this.wfTASK;
	}

	public void setWfTASK(String wfSection) {
		this.wfTASK = wfSection;
	}

	@Column(name = "WF_VER", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getWfVer() {
		return this.wfVer;
	}

	public void setWfVer(String wfVer) {
		this.wfVer = wfVer;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

}
