package com.dgsoft.common.system.model;
// Generated Apr 28, 2013 11:02:59 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "REPORT", catalog = "DG_SYSTEM")
public class Report implements java.io.Serializable {

	private String id;
	private Integer version;
	private String name;
	private boolean nesting;
	private String location;
	private String nestingLocation;
	private int priority;
	private String memo;
	public Report() {
	}

	public Report(String id, boolean nesting, int priority) {
		this.id = id;
		this.nesting = nesting;
		this.priority = priority;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "NAME", length = 50)
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NESTING", nullable = false)
	public boolean isNesting() {
		return this.nesting;
	}

	public void setNesting(boolean nesting) {
		this.nesting = nesting;
	}

	@Column(name = "LOCATION", length = 100)
	@Size(max = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "NESTING_LOCATION", length = 100)
	@Size(max = 100)
	public String getNestingLocation() {
		return this.nestingLocation;
	}

	public void setNestingLocation(String nestingLocation) {
		this.nestingLocation = nestingLocation;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
