package com.dgsoft.common.system.model;
// Generated Apr 28, 2013 11:02:59 AM by Hibernate Tools 4.0.0

import com.dgsoft.common.OrderModel;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "ROLE", catalog = "DG_SYSTEM")
public class Role implements java.io.Serializable, OrderModel {

    private String id;
    private String name;
    private String description;
    private int priority;

    private Set<BusinessDefine> businessDefines = new HashSet<BusinessDefine>(0);
    private Set<Function> functions = new HashSet<Function>(0);

    public Role() {
    }

    public Role(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public Role(String id, String name,
                String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "NAME", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 200)
    @Size(max = 200)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY, targetEntity = BusinessDefine.class)
    @JoinTable(name = "ROLE_BIZ", joinColumns = @JoinColumn(name = "ROLE_ID"), inverseJoinColumns = @JoinColumn(name = "BIZ_ID"))
    public Set<BusinessDefine> getBusinessDefines() {
        return businessDefines;
    }

    public void setBusinessDefines(Set<BusinessDefine> businessDefines) {
        this.businessDefines = businessDefines;
    }

    @Override
    @Column(name = "PRIORITY",nullable = false)
    @NotNull
    public int getPriority() {
        return this.priority;
    }

    @Override
    public void setPriority(int priority) {
        this.priority = priority;
    }

    @ManyToMany(fetch = FetchType.LAZY, targetEntity = Function.class)
    @JoinTable(name = "ROLE_FUNCTION", joinColumns = @JoinColumn(name = "ROL_ID"), inverseJoinColumns = @JoinColumn(name = "FUN_ID"))
    public Set<Function> getFunctions() {
        return functions;
    }

    public void setFunctions(Set<Function> functions) {
        this.functions = functions;
    }

    @Override
    @Transient
    public int hashCode(){
        return id.hashCode();
    }

    @Override
    @Transient
    public boolean equals(Object obj){
        if (obj == null){
            return false;
        }
        if (!(obj instanceof Role)){
            return false;
        }
        return id.equals(((Role) obj).getId());
    }


}
