package com.dgsoft.erp.model;
// Generated Nov 5, 2013 1:58:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * AccountingType generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNTING_TYPE", catalog = "MINI_ERP")
public class AccountingType implements java.io.Serializable {

	private String id;
	private String name;
	private String balanceDirectoin;
	private Set<Accounting> accountings = new HashSet<Accounting>(0);


	public AccountingType() {
	}

	public AccountingType(String id, String name, String balanceDirectoin) {
		this.id = id;
		this.name = name;
		this.balanceDirectoin = balanceDirectoin;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "BALANCE_DIRECTOIN", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getBalanceDirectoin() {
		return this.balanceDirectoin;
	}

	public void setBalanceDirectoin(String balanceDirectoin) {
		this.balanceDirectoin = balanceDirectoin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountingType")
	public Set<Accounting> getAccountings() {
		return this.accountings;
	}

	public void setAccountings(Set<Accounting> accountings) {
		this.accountings = accountings;
	}

}
