package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Accounting generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNTING", catalog = "MINI_ERP")
public class Accounting implements java.io.Serializable {

	private String id;
	private String name;
	private String subjectNo;
	private boolean debit;
    private Res res;
	private Set<AccountOper> accountOpersForDebit = new HashSet<AccountOper>(0);
	private Set<MiddleMoney> middleMoneysForCredit = new HashSet<MiddleMoney>(0);
	private Set<MiddleMoney> middleMoneysForDebit = new HashSet<MiddleMoney>(0);
	private Set<AccountOper> accountOpersForCredit = new HashSet<AccountOper>(0);

	public Accounting() {
	}

	public Accounting(String id, String name, String subjectNo, boolean debit) {
		this.id = id;
		this.name = name;
		this.subjectNo = subjectNo;
		this.debit = debit;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SUBJECT_NO", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getSubjectNo() {
		return this.subjectNo;
	}

	public void setSubjectNo(String subjectNo) {
		this.subjectNo = subjectNo;
	}

	@Column(name = "DEBIT", nullable = false)
	public boolean isDebit() {
		return this.debit;
	}

	public void setDebit(boolean debit) {
		this.debit = debit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountingByDebit")
	public Set<AccountOper> getAccountOpersForDebit() {
		return this.accountOpersForDebit;
	}

	public void setAccountOpersForDebit(Set<AccountOper> accountOpersForDebit) {
		this.accountOpersForDebit = accountOpersForDebit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountingByCredit")
	public Set<MiddleMoney> getMiddleMoneysForCredit() {
		return this.middleMoneysForCredit;
	}

	public void setMiddleMoneysForCredit(Set<MiddleMoney> middleMoneysForCredit) {
		this.middleMoneysForCredit = middleMoneysForCredit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountingByDebit")
	public Set<MiddleMoney> getMiddleMoneysForDebit() {
		return this.middleMoneysForDebit;
	}

	public void setMiddleMoneysForDebit(Set<MiddleMoney> middleMoneysForDebit) {
		this.middleMoneysForDebit = middleMoneysForDebit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountingByCredit")
	public Set<AccountOper> getAccountOpersForCredit() {
		return this.accountOpersForCredit;
	}

	public void setAccountOpersForCredit(Set<AccountOper> accountOpersForCredit) {
		this.accountOpersForCredit = accountOpersForCredit;
	}

    @OneToOne(optional = true, fetch = FetchType.LAZY, mappedBy = "accounting")
    public Res getRes() {
        return res;
    }

    public void setRes(Res res) {
        this.res = res;
    }
}
