package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BackRes generated by hbm2java
 */
@Entity
@Table(name = "BACK_RES", catalog = "MINI_ERP")
public class BackRes implements java.io.Serializable {

	private String id;
	private OrderBack orderBack;
	private StoreIn storeIn;
	private String memo;

	public BackRes() {
	}

	public BackRes(String id, OrderBack orderBack, StoreIn storeIn) {
		this.id = id;
		this.orderBack = orderBack;
		this.storeIn = storeIn;
	}
	public BackRes(String id, OrderBack orderBack, StoreIn storeIn, String memo) {
		this.id = id;
		this.orderBack = orderBack;
		this.storeIn = storeIn;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public OrderBack getOrderBack() {
		return this.orderBack;
	}

	public void setOrderBack(OrderBack orderBack) {
		this.orderBack = orderBack;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_IN", nullable = false)
	@NotNull
	public StoreIn getStoreIn() {
		return this.storeIn;
	}

	public void setStoreIn(StoreIn storeIn) {
		this.storeIn = storeIn;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
