package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BackMoney generated by hbm2java
 */
@Entity
@Table(name = "BACK_MONEY", catalog = "MINI_ERP")
public class BackMoney implements java.io.Serializable {

	private String id;
	private OrderBack orderBack;
	private AccountOper accountOper;

	public BackMoney() {
	}

	public BackMoney(String id, OrderBack orderBack, AccountOper accountOper) {
		this.id = id;
		this.orderBack = orderBack;
		this.accountOper = accountOper;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BACK_ORDER", nullable = false)
	@NotNull
	public OrderBack getOrderBack() {
		return this.orderBack;
	}

	public void setOrderBack(OrderBack orderBack) {
		this.orderBack = orderBack;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_OPER", nullable = false)
	@NotNull
	public AccountOper getAccountOper() {
		return this.accountOper;
	}

	public void setAccountOper(AccountOper accountOper) {
		this.accountOper = accountOper;
	}

}
