package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "CAR", catalog = "MINI_ERP")
public class Car implements java.io.Serializable {

	private String id;
	private Integer version;
	private boolean idle;
	private String defaultDriver;
	private boolean enable;
	private Set<DeliveryCar> deliveryCars = new HashSet<DeliveryCar>(0);

	public Car() {
	}

	public Car(String id, boolean idle, boolean enable) {
		this.id = id;
		this.idle = idle;
		this.enable = enable;
	}
	public Car(String id, boolean idle, String defaultDriver, boolean enable,
			Set<DeliveryCar> deliveryCars) {
		this.id = id;
		this.idle = idle;
		this.defaultDriver = defaultDriver;
		this.enable = enable;
		this.deliveryCars = deliveryCars;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "IDLE", nullable = false)
	public boolean isIdle() {
		return this.idle;
	}

	public void setIdle(boolean idle) {
		this.idle = idle;
	}

	@Column(name = "DEFAULT_DRIVER", length = 32)
	@Size(max = 32)
	public String getDefaultDriver() {
		return this.defaultDriver;
	}

	public void setDefaultDriver(String defaultDriver) {
		this.defaultDriver = defaultDriver;
	}

	@Column(name = "ENABLE", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<DeliveryCar> getDeliveryCars() {
		return this.deliveryCars;
	}

	public void setDeliveryCars(Set<DeliveryCar> deliveryCars) {
		this.deliveryCars = deliveryCars;
	}

}
