package com.dgsoft.erp.model;
// Generated Oct 24, 2013 3:27:02 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Cars generated by hbm2java
 */
@Entity
@Table(name = "CARS", catalog = "MINI_ERP")
public class Cars implements java.io.Serializable {

	private String id;
	private Employee employee;
	private Set<ProductToDoor> productToDoors = new HashSet<ProductToDoor>(0);

	public Cars() {
	}

	public Cars(String id, Employee employee) {
		this.id = id;
		this.employee = employee;
	}
	public Cars(String id, Employee employee, Set<ProductToDoor> productToDoors) {
		this.id = id;
		this.employee = employee;
		this.productToDoors = productToDoors;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEFAULT_DRIVER", nullable = false)
	@NotNull
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cars")
	public Set<ProductToDoor> getProductToDoors() {
		return this.productToDoors;
	}

	public void setProductToDoors(Set<ProductToDoor> productToDoors) {
		this.productToDoors = productToDoors;
	}

}
