package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DeliveryCar generated by hbm2java
 */
@Entity
@Table(name = "DELIVERY_CAR", catalog = "MINI_ERP")
public class DeliveryCar implements java.io.Serializable {

	private String id;
	private OrderDelivery orderDelivery;
	private Car car;
	private String driver;

	public DeliveryCar() {
	}

	public DeliveryCar(String id, OrderDelivery orderDelivery, Car car,
			String driver) {
		this.id = id;
		this.orderDelivery = orderDelivery;
		this.car = car;
		this.driver = driver;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DELIVERY_ID", nullable = false)
	@NotNull
	public OrderDelivery getOrderDelivery() {
		return this.orderDelivery;
	}

	public void setOrderDelivery(OrderDelivery orderDelivery) {
		this.orderDelivery = orderDelivery;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAR", nullable = false)
	@NotNull
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Column(name = "DRIVER", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

}
