package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Depositary generated by hbm2java
 */
@Entity
@Table(name = "DEPOSITARY", catalog = "MINI_ERP")
public class Depositary implements java.io.Serializable {

	private String id;
	private Integer version;
	private StoreArea storeArea;
	private BatchStoreCount batchStoreCount;
	private Stock stock;
	private BigDecimal count;

	public Depositary() {
	}

	public Depositary(String id, StoreArea storeArea,
			BatchStoreCount batchStoreCount, Stock stock, BigDecimal count) {
		this.id = id;
		this.storeArea = storeArea;
		this.batchStoreCount = batchStoreCount;
		this.stock = stock;
		this.count = count;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_AREA", nullable = false)
	@NotNull
	public StoreArea getStoreArea() {
		return this.storeArea;
	}

	public void setStoreArea(StoreArea storeArea) {
		this.storeArea = storeArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BATCH", nullable = false)
	@NotNull
	public BatchStoreCount getBatchStoreCount() {
		return this.batchStoreCount;
	}

	public void setBatchStoreCount(BatchStoreCount batchStoreCount) {
		this.batchStoreCount = batchStoreCount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK", nullable = false)
	@NotNull
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Column(name = "COUNT", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

}
