package com.dgsoft.erp.model;
// Generated Oct 28, 2013 12:46:39 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Dispatch generated by hbm2java
 */
@Entity
@Table(name = "DISPATCH", catalog = "MINI_ERP")
public class Dispatch implements java.io.Serializable {

	private String id;
    private Store store;
	private DispatchItem dispatchItem;
	private CustomerOrder customerOrder;
	private OrderDelivery orderDelivery;

	public Dispatch() {
	}



	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE", nullable = false)
	@NotNull
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMS", nullable = false)
	@NotNull
	public DispatchItem getDispatchItem() {
		return this.dispatchItem;
	}

	public void setDispatchItem(DispatchItem dispatchItem) {
		this.dispatchItem = dispatchItem;
	}

	@OneToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_DELIVERY")
	public OrderDelivery getOrderDelivery() {
		return this.orderDelivery;
	}

	public void setOrderDelivery(OrderDelivery orderDelivery) {
		this.orderDelivery = orderDelivery;
	}

}
