package com.dgsoft.erp.model;
// Generated Oct 30, 2013 1:46:18 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DispatchItem generated by hbm2java
 */
@Entity
@Table(name = "DISPATCH_ITEM", catalog = "MINI_ERP")
public class DispatchItem implements java.io.Serializable {

	private String id;
	private OrderItem orderItem;
	private BigDecimal count;
	private Dispatch dispatch;
    private Set<StoreRes> storeReses = new HashSet<StoreRes>(0);

	public DispatchItem() {
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ITEM", nullable = false)
	@NotNull
	public OrderItem getOrderItem() {
		return this.orderItem;
	}

	public void setOrderItem(OrderItem orderItem) {
		this.orderItem = orderItem;
	}

	@Column(name = "COUNT", scale = 4)
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

    @ManyToOne(optional = false,fetch = FetchType.LAZY)
    @JoinColumn(name = "DISPATCH", nullable = false)
    @NotNull
    public Dispatch getDispatch() {
        return dispatch;
    }

    public void setDispatch(Dispatch dispatch) {
        this.dispatch = dispatch;
    }

    @ManyToMany(fetch = FetchType.LAZY, targetEntity = StoreRes.class)
    @JoinTable(name = "DISPATCH_RES_ITEM", joinColumns = @JoinColumn(name = "ITEM"), inverseJoinColumns = @JoinColumn(name = "STORE_RES"))
    public Set<StoreRes> getStoreReses() {
        return storeReses;
    }

    public void setStoreReses(Set<StoreRes> storeReses) {
        this.storeReses = storeReses;
    }
}
