package com.dgsoft.erp.model;
// Generated Oct 24, 2013 3:27:02 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE", catalog = "MINI_ERP")
public class Employee implements java.io.Serializable {

	private String id;
	private String name;
	private String tel;
	private Set<Cars> carses = new HashSet<Cars>(0);
	private Set<ProductToDoor> productToDoors = new HashSet<ProductToDoor>(0);

	public Employee() {
	}

	public Employee(String id, String name) {
		this.id = id;
		this.name = name;
	}
	public Employee(String id, String name, String tel, Set<Cars> carses,
			Set<ProductToDoor> productToDoors) {
		this.id = id;
		this.name = name;
		this.tel = tel;
		this.carses = carses;
		this.productToDoors = productToDoors;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TEL", length = 50)
	@Size(max = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Cars> getCarses() {
		return this.carses;
	}

	public void setCarses(Set<Cars> carses) {
		this.carses = carses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<ProductToDoor> getProductToDoors() {
		return this.productToDoors;
	}

	public void setProductToDoors(Set<ProductToDoor> productToDoors) {
		this.productToDoors = productToDoors;
	}

}
