package com.dgsoft.erp.model;
// Generated Oct 24, 2013 3:27:02 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ExpressCar generated by hbm2java
 */
@Entity
@Table(name = "EXPRESS_CAR", catalog = "MINI_ERP")
public class ExpressCar implements java.io.Serializable {

	private String id;
	private ExpressDriver expressDriver;
	private String carCode;
	private Set<OrderDelivery> orderDeliveries = new HashSet<OrderDelivery>(0);

	public ExpressCar() {
	}

	public ExpressCar(String id, ExpressDriver expressDriver) {
		this.id = id;
		this.expressDriver = expressDriver;
	}
	public ExpressCar(String id, ExpressDriver expressDriver, String carCode,
			Set<OrderDelivery> orderDeliveries) {
		this.id = id;
		this.expressDriver = expressDriver;
		this.carCode = carCode;
		this.orderDeliveries = orderDeliveries;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DRIVER", nullable = false)
	@NotNull
	public ExpressDriver getExpressDriver() {
		return this.expressDriver;
	}

	public void setExpressDriver(ExpressDriver expressDriver) {
		this.expressDriver = expressDriver;
	}

	@Column(name = "CAR_CODE", length = 20)
	@Size(max = 20)
	public String getCarCode() {
		return this.carCode;
	}

	public void setCarCode(String carCode) {
		this.carCode = carCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expressCar")
	public Set<OrderDelivery> getOrderDeliveries() {
		return this.orderDeliveries;
	}

	public void setOrderDeliveries(Set<OrderDelivery> orderDeliveries) {
		this.orderDeliveries = orderDeliveries;
	}

}
