package com.dgsoft.erp.model;
// Generated Oct 30, 2013 1:46:18 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.GenericGenerator;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ExpressCar generated by hbm2java
 */
@Entity
@Table(name = "EXPRESS_CAR", catalog = "MINI_ERP")
public class ExpressCar implements java.io.Serializable {

	private String id;
	private ExpressDriver expressDriver;
	private String carCode;
	private Dispatch dispatch;

	public ExpressCar() {
	}

	public ExpressCar(Dispatch dispatch, ExpressDriver expressDriver) {
		this.expressDriver = expressDriver;
        this.dispatch = dispatch;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.PERSIST})
	@JoinColumn(name = "DRIVER", nullable = false)
	@NotNull
	public ExpressDriver getExpressDriver() {
		return this.expressDriver;
	}

	public void setExpressDriver(ExpressDriver expressDriver) {
		this.expressDriver = expressDriver;
	}

	@Column(name = "CAR_CODE", length = 20)
	@Size(max = 20)
	public String getCarCode() {
		return this.carCode;
	}

	public void setCarCode(String carCode) {
		this.carCode = carCode;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "expressCar")
	public Dispatch getDispatch() {
		return this.dispatch;
	}

	public void setDispatch(Dispatch dispatches) {
		this.dispatch = dispatches;
	}

}
