package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ExpressInfo generated by hbm2java
 */
@Entity
@Table(name = "EXPRESS_INFO", catalog = "MINI_ERP")
public class ExpressInfo implements java.io.Serializable {

	private String id;
	private TransCorp transCorp;
	private OrderDelivery orderDelivery;
	private String number;

	public ExpressInfo() {
	}

	public ExpressInfo(String id, TransCorp transCorp,
			OrderDelivery orderDelivery) {
		this.id = id;
		this.transCorp = transCorp;
		this.orderDelivery = orderDelivery;
	}
	public ExpressInfo(String id, TransCorp transCorp,
			OrderDelivery orderDelivery, String number) {
		this.id = id;
		this.transCorp = transCorp;
		this.orderDelivery = orderDelivery;
		this.number = number;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANS", nullable = false)
	@NotNull
	public TransCorp getTransCorp() {
		return this.transCorp;
	}

	public void setTransCorp(TransCorp transCorp) {
		this.transCorp = transCorp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DELIVERY", nullable = false)
	@NotNull
	public OrderDelivery getOrderDelivery() {
		return this.orderDelivery;
	}

	public void setOrderDelivery(OrderDelivery orderDelivery) {
		this.orderDelivery = orderDelivery;
	}

	@Column(name = "NUMBER", length = 50)
	@Size(max = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

}
