package com.dgsoft.erp.model;
// Generated Oct 30, 2013 1:46:18 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ExpressInfo generated by hbm2java
 */
@Entity
@Table(name = "EXPRESS_INFO", catalog = "MINI_ERP")
public class ExpressInfo implements java.io.Serializable {

	private String id;
	private TransCorp transCorp;
	private String number;
	private Set<Dispatch> dispatches = new HashSet<Dispatch>(0);

	public ExpressInfo() {
	}

	public ExpressInfo(String id, TransCorp transCorp) {
		this.id = id;
		this.transCorp = transCorp;
	}
	public ExpressInfo(String id, TransCorp transCorp, String number,
			Set<Dispatch> dispatches) {
		this.id = id;
		this.transCorp = transCorp;
		this.number = number;
		this.dispatches = dispatches;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANS", nullable = false)
	@NotNull
	public TransCorp getTransCorp() {
		return this.transCorp;
	}

	public void setTransCorp(TransCorp transCorp) {
		this.transCorp = transCorp;
	}

	@Column(name = "NUMBER", length = 50)
	@Size(max = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expressInfo")
	public Set<Dispatch> getDispatches() {
		return this.dispatches;
	}

	public void setDispatches(Set<Dispatch> dispatches) {
		this.dispatches = dispatches;
	}

}
