package com.dgsoft.erp.model;
// Generated Nov 9, 2014 12:57:57 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * InventoryItemId generated by hbm2java
 */
@Embeddable
public class InventoryItemId implements java.io.Serializable {

	private String inventory;
	private String stock;

	public InventoryItemId() {
	}

	public InventoryItemId(String inventory, String stock) {
		this.inventory = inventory;
		this.stock = stock;
	}

	@Column(name = "INVENTORY", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getInventory() {
		return this.inventory;
	}

	public void setInventory(String inventory) {
		this.inventory = inventory;
	}

	@Column(name = "STOCK", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getStock() {
		return this.stock;
	}

	public void setStock(String stock) {
		this.stock = stock;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryItemId))
			return false;
		InventoryItemId castOther = (InventoryItemId) other;

		return ((this.getInventory() == castOther.getInventory()) || (this
				.getInventory() != null
				&& castOther.getInventory() != null && this.getInventory()
				.equals(castOther.getInventory())))
				&& ((this.getStock() == castOther.getStock()) || (this
						.getStock() != null
						&& castOther.getStock() != null && this.getStock()
						.equals(castOther.getStock())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getInventory() == null ? 0 : this.getInventory().hashCode());
		result = 37 * result
				+ (getStock() == null ? 0 : this.getStock().hashCode());
		return result;
	}

}
