package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name = "INVENTORY", catalog = "MINI_ERP")
public class Inventory implements java.io.Serializable {

    public enum InventoryType{
        MONTH_INVENTORY,YEAR_INVENTORY,RANDOM_INVENTORY;
    }

    public enum InvertoryStatus{
        STORE_INVERTORY,CHECKING,INVERTORY_COMPLETE;
    }

	private String id;
	private Store store;
	private StockChange stockChangeLoss;
	private StockChange stockChangeAdd;
	private Date checkDate;
    private Date checkedDate;
    private Date applyDate;
	private String memo;
    private InventoryType type;
    private String applyEmp;
    private boolean stockChanged;
    private String checkEmp;
    private InvertoryStatus status;
    private Set<InventoryItem> inventoryItems = new HashSet<InventoryItem>(0);

	public Inventory() {
	}

    public Inventory(String id, String applyEmp) {
        this.id = id;
        this.applyDate = new Date();
        this.checkDate = new Date();
        this.applyEmp = applyEmp;
        status = InvertoryStatus.STORE_INVERTORY;
        stockChanged = false;
    }

    public Inventory(boolean stockChanged){
        stockChanged = false;
    }

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE", nullable = false)
	@NotNull
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}


    @ManyToOne(optional = true, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "LOSS_RES", unique = true, nullable = true, updatable = true)
	public StockChange getStockChangeLoss() {
		return this.stockChangeLoss;
	}

	public void setStockChangeLoss(StockChange stockChangeByLossRes) {
		this.stockChangeLoss = stockChangeByLossRes;
	}

    @ManyToOne(optional = true, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "ADD_RES", unique = true, nullable = true, updatable = true)
	public StockChange getStockChangeAdd() {
		return this.stockChangeAdd;
	}

	public void setStockChangeAdd(StockChange stockChangeByAddRes) {
		this.stockChangeAdd = stockChangeByAddRes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHECK_DATE", nullable = false, length = 19)
    @NotNull
	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CHECKED_DATE", nullable = true, length = 19)
    public Date getCheckedDate() {
        return checkedDate;
    }

    public void setCheckedDate(Date checkedDate) {
        this.checkedDate = checkedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "APPLY_DATE", nullable = false, length = 19)
    @NotNull
    public Date getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    @Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}


    @Enumerated(EnumType.STRING)
    @Column(name = "TYPE",nullable = false,length = 32)
    @NotNull
    public InventoryType getType() {

        return type;
    }

    public void setType(InventoryType type) {
        this.type = type;
    }

    @Column(name = "STOCK_CHANGED",nullable = false)
    public boolean isStockChanged() {
        return stockChanged;
    }

    public void setStockChanged(boolean stockChanged) {
        this.stockChanged = stockChanged;
    }

    @Column(name="APPLY_EMP",nullable = false,length = 32)
    @NotNull
    @Size(max = 32)
    public String getApplyEmp() {
        return applyEmp;
    }

    public void setApplyEmp(String applyEmp) {
        this.applyEmp = applyEmp;
    }


    @Column(name="CHECK_EMP",nullable = true,length = 32)
    @Size(max = 32)
    public String getCheckEmp() {
        return checkEmp;
    }

    public void setCheckEmp(String checkEmp) {
        this.checkEmp = checkEmp;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "inventory" , cascade = CascadeType.ALL , orphanRemoval = true)
    public Set<InventoryItem> getInventoryItems() {
        return inventoryItems;
    }

    public void setInventoryItems(Set<InventoryItem> inventoryItems) {
        this.inventoryItems = inventoryItems;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "STATUS",nullable = false,length = 20)
    @NotNull
    public InvertoryStatus getStatus() {
        return status;
    }

    public void setStatus(InvertoryStatus status) {
        this.status = status;
    }
}
