package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MaterialBackStoreIn generated by hbm2java
 */
@Entity
@Table(name = "MATERIAL_BACK_STORE_IN", catalog = "MINI_ERP")
public class MaterialBackStoreIn implements java.io.Serializable {

	private String id;
	private StockChange stockChange;
	private String reason;
	private String description;

	public MaterialBackStoreIn() {
	}

	public MaterialBackStoreIn(String id, StockChange stockChange, String reason) {
		this.id = id;
		this.stockChange = stockChange;
		this.reason = reason;
	}
	public MaterialBackStoreIn(String id, StockChange stockChange,
			String reason, String description) {
		this.id = id;
		this.stockChange = stockChange;
		this.reason = reason;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_CHANGE", nullable = false)
	@NotNull
	public StockChange getStockChange() {
		return this.stockChange;
	}

	public void setStockChange(StockChange stockChange) {
		this.stockChange = stockChange;
	}

	@Column(name = "REASON", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "DESCRIPTION", length = 200)
	@Size(max = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
