package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MaterialStoreOut generated by hbm2java
 */
@Entity
@Table(name = "MATERIAL_STORE_OUT", catalog = "MINI_ERP")
public class MaterialStoreOut implements java.io.Serializable {

	private String id;
	private Batch batch;
	private String receiveEmp;
    private StockChange stockChange;

	public MaterialStoreOut() {
	}

	public MaterialStoreOut(String id, Batch batch) {
		this.id = id;
		this.batch = batch;
	}
	public MaterialStoreOut(String id, Batch batch, String receiveEmp) {
		this.id = id;
		this.batch = batch;
		this.receiveEmp = receiveEmp;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_BATCH", nullable = true)
	public Batch getBatch() {
		return this.batch;
	}

	public void setBatch(Batch batch) {
		this.batch = batch;
	}

	@Column(name = "RECEIVE_EMP", length = 32)
	@Size(max = 32)
	public String getReceiveEmp() {
		return this.receiveEmp;
	}

	public void setReceiveEmp(String receiveEmp) {
		this.receiveEmp = receiveEmp;
	}

    @ManyToOne(optional = true, fetch = FetchType.LAZY)
    @JoinColumn(name = "STORE_CHANGE", nullable = false)
    @NotNull
    public StockChange getStockChange() {
        return this.stockChange;
    }

    public void setStockChange(StockChange stockChange) {
        this.stockChange = stockChange;
    }

}
