package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import com.dgsoft.erp.model.api.StockChangeModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MaterialStoreIn generated by hbm2java
 */
@Entity
@Table(name = "MATERIAL_STORE_IN", catalog = "MINI_ERP")
public class MaterialStoreIn implements java.io.Serializable, StockChangeModel {

	private String id;
	private StockChange stockChange;
	private String checkEmp;

	public MaterialStoreIn() {
	}

	public MaterialStoreIn(String id, StockChange stockChange) {
		this.id = id;
		this.stockChange = stockChange;
	}
	public MaterialStoreIn(String id, StockChange stockChange, String checkEmp) {
		this.id = id;
		this.stockChange = stockChange;
		this.checkEmp = checkEmp;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_CHANGE", nullable = false)
	@NotNull
	public StockChange getStockChange() {
		return this.stockChange;
	}

	public void setStockChange(StockChange stockChange) {
		this.stockChange = stockChange;
	}

	@Column(name = "CHECK_EMP", length = 32)
	@Size(max = 32)
	public String getCheckEmp() {
		return this.checkEmp;
	}

	public void setCheckEmp(String checkEmp) {
		this.checkEmp = checkEmp;
	}

}
