package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MiddleMoneyPay generated by hbm2java
 */
@Entity
@Table(name = "MIDDLE_MONEY_PAY", catalog = "MINI_ERP")
public class MiddleMoneyPay implements java.io.Serializable {

	private String id;
	private CustomerOrder customerOrder;
	private Accounting accountingByDebit;
	private Accounting accountingByCredit;
	private MiddleMan middleMan;
	private BigDecimal money;
	private Date operDate;
	private String operEmp;
	private String description;

	public MiddleMoneyPay() {
	}

	public MiddleMoneyPay(String id, CustomerOrder customerOrder,
                          MiddleMan middleMan, BigDecimal money, Date operDate, String operEmp) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.middleMan = middleMan;
		this.money = money;
		this.operDate = operDate;
		this.operEmp = operEmp;
	}
	public MiddleMoneyPay(String id, CustomerOrder customerOrder,
                          Accounting accountingByDebit, Accounting accountingByCredit,
                          MiddleMan middleMan, BigDecimal money, Date operDate,
                          String operEmp, String description) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.accountingByDebit = accountingByDebit;
		this.accountingByCredit = accountingByCredit;
		this.middleMan = middleMan;
		this.money = money;
		this.operDate = operDate;
		this.operEmp = operEmp;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEBIT")
	public Accounting getAccountingByDebit() {
		return this.accountingByDebit;
	}

	public void setAccountingByDebit(Accounting accountingByDebit) {
		this.accountingByDebit = accountingByDebit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREDIT")
	public Accounting getAccountingByCredit() {
		return this.accountingByCredit;
	}

	public void setAccountingByCredit(Accounting accountingByCredit) {
		this.accountingByCredit = accountingByCredit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MIDDLE_MAN", nullable = false)
	@NotNull
	public MiddleMan getMiddleMan() {
		return this.middleMan;
	}

	public void setMiddleMan(MiddleMan middleMan) {
		this.middleMan = middleMan;
	}

	@Column(name = "MONEY", nullable = false, scale = 3)
	@NotNull
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPER_DATE", nullable = false, length = 19)
	@NotNull
	public Date getOperDate() {
		return this.operDate;
	}

	public void setOperDate(Date operDate) {
		this.operDate = operDate;
	}

	@Column(name = "OPER_EMP", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getOperEmp() {
		return this.operEmp;
	}

	public void setOperEmp(String operEmp) {
		this.operEmp = operEmp;
	}

	@Column(name = "DESCRIPTION", length = 200)
	@Size(max = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
