package com.dgsoft.erp.model;
// Generated Oct 30, 2013 1:46:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * NeedRes generated by hbm2java
 */
@Entity
@Table(name = "NEED_RES", catalog = "MINI_ERP")
public class NeedRes implements java.io.Serializable {

	private String id;
	private CustomerOrder customerOrder;
	private String type;
	private Date limitTime;
	private String reason;
	private String memo;
	private Date createDate;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<Dispatch> dispatches = new HashSet<Dispatch>(0);

	public NeedRes() {
	}

	public NeedRes(String id, CustomerOrder customerOrder, String type,
			Date limitTime, String reason, Date createDate) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.type = type;
		this.limitTime = limitTime;
		this.reason = reason;
		this.createDate = createDate;
	}
	public NeedRes(String id, CustomerOrder customerOrder, String type,
			Date limitTime, String reason, String memo, Date createDate,
			Set<OrderItem> orderItems, Set<Dispatch> dispatches) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.type = type;
		this.limitTime = limitTime;
		this.reason = reason;
		this.memo = memo;
		this.createDate = createDate;
		this.orderItems = orderItems;
		this.dispatches = dispatches;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@Column(name = "TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LIMIT_TIME", nullable = false, length = 19)
	@NotNull
	public Date getLimitTime() {
		return this.limitTime;
	}

	public void setLimitTime(Date limitTime) {
		this.limitTime = limitTime;
	}

	@Column(name = "REASON", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "needRes")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "needRes")
	public Set<Dispatch> getDispatches() {
		return this.dispatches;
	}

	public void setDispatches(Set<Dispatch> dispatches) {
		this.dispatches = dispatches;
	}

}
