package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderDelivery generated by hbm2java
 */
@Entity
@Table(name = "ORDER_DELIVERY", catalog = "MINI_ERP")
public class OrderDelivery implements java.io.Serializable {

	private String id;
	private CustomerOrder customerOrder;
	private StoreOut storeOut;
	private String deliveryType;
	private String memo;
	private Set<ExpressInfo> expressInfos = new HashSet<ExpressInfo>(0);
	private Set<DeliveryCar> deliveryCars = new HashSet<DeliveryCar>(0);

	public OrderDelivery() {
	}

	public OrderDelivery(String id, CustomerOrder customerOrder,
			StoreOut storeOut, String deliveryType) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.storeOut = storeOut;
		this.deliveryType = deliveryType;
	}
	public OrderDelivery(String id, CustomerOrder customerOrder,
			StoreOut storeOut, String deliveryType, String memo,
			Set<ExpressInfo> expressInfos, Set<DeliveryCar> deliveryCars) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.storeOut = storeOut;
		this.deliveryType = deliveryType;
		this.memo = memo;
		this.expressInfos = expressInfos;
		this.deliveryCars = deliveryCars;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_OUT", nullable = false)
	@NotNull
	public StoreOut getStoreOut() {
		return this.storeOut;
	}

	public void setStoreOut(StoreOut storeOut) {
		this.storeOut = storeOut;
	}

	@Column(name = "DELIVERY_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderDelivery")
	public Set<ExpressInfo> getExpressInfos() {
		return this.expressInfos;
	}

	public void setExpressInfos(Set<ExpressInfo> expressInfos) {
		this.expressInfos = expressInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderDelivery")
	public Set<DeliveryCar> getDeliveryCars() {
		return this.deliveryCars;
	}

	public void setDeliveryCars(Set<DeliveryCar> deliveryCars) {
		this.deliveryCars = deliveryCars;
	}

}
