package com.dgsoft.erp.model;
// Generated Oct 24, 2013 3:27:02 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderList generated by hbm2java
 */
@Entity
@Table(name = "ORDER_LIST", catalog = "MINI_ERP")
public class OrderList implements java.io.Serializable {

	private String id;
	private Res res;
	private CustomerOrder customerOrder;
	private BigDecimal count;
	private BigDecimal cost;
	private BigDecimal floatConversionRate;

	public OrderList() {
	}

	public OrderList(String id, Res res, CustomerOrder customerOrder,
			BigDecimal count) {
		this.id = id;
		this.res = res;
		this.customerOrder = customerOrder;
		this.count = count;
	}
	public OrderList(String id, Res res, CustomerOrder customerOrder,
			BigDecimal count, BigDecimal cost, BigDecimal floatConversionRate) {
		this.id = id;
		this.res = res;
		this.customerOrder = customerOrder;
		this.count = count;
		this.cost = cost;
		this.floatConversionRate = floatConversionRate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RES", nullable = false)
	@NotNull
	public Res getRes() {
		return this.res;
	}

	public void setRes(Res res) {
		this.res = res;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@Column(name = "COUNT", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	@Column(name = "COST", scale = 3)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "FLOAT_CONVERSION_RATE", scale = 10)
	public BigDecimal getFloatConversionRate() {
		return this.floatConversionRate;
	}

	public void setFloatConversionRate(BigDecimal floatConversionRate) {
		this.floatConversionRate = floatConversionRate;
	}

}
