package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderBack generated by hbm2java
 */
@Entity
@Table(name = "ORDER_BACK", catalog = "MINI_ERP")
public class OrderBack implements java.io.Serializable {

	private String id;
	private Integer version;
	private CustomerOrder customerOrder;
	private String state;
	private String reason;
	private Date createDate;
	private Date completeDate;
	private String processMessage;
	private String memo;
	private Set<BackRes> backReses = new HashSet<BackRes>(0);
	private Set<BackMoney> backMoneys = new HashSet<BackMoney>(0);

	public OrderBack() {
	}

	public OrderBack(String id, CustomerOrder customerOrder, String state,
			String reason, Date createDate, Date completeDate) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.state = state;
		this.reason = reason;
		this.createDate = createDate;
		this.completeDate = completeDate;
	}
	public OrderBack(String id, CustomerOrder customerOrder, String state,
			String reason, Date createDate, Date completeDate,
			String processMessage, String memo, Set<BackRes> backReses,
			Set<BackMoney> backMoneys) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.state = state;
		this.reason = reason;
		this.createDate = createDate;
		this.completeDate = completeDate;
		this.processMessage = processMessage;
		this.memo = memo;
		this.backReses = backReses;
		this.backMoneys = backMoneys;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@Column(name = "STATE", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "REASON", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMPLETE_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCompleteDate() {
		return this.completeDate;
	}

	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

	@Column(name = "PROCESS_MESSAGE", length = 500)
	@Size(max = 500)
	public String getProcessMessage() {
		return this.processMessage;
	}

	public void setProcessMessage(String processMessage) {
		this.processMessage = processMessage;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderBack")
	public Set<BackRes> getBackReses() {
		return this.backReses;
	}

	public void setBackReses(Set<BackRes> backReses) {
		this.backReses = backReses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderBack")
	public Set<BackMoney> getBackMoneys() {
		return this.backMoneys;
	}

	public void setBackMoneys(Set<BackMoney> backMoneys) {
		this.backMoneys = backMoneys;
	}

}
