package com.dgsoft.erp.model;
// Generated Nov 15, 2013 4:00:38 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderFee generated by hbm2java
 */
@Entity
@Table(name = "ORDER_FEE", catalog = "MINI_ERP")
public class OrderFee implements java.io.Serializable {

	private String id;
	private BigDecimal money;
	private String description;
	private boolean pay;
	private CustomerOrder customerOrder;
	private String payType;
	private String checkNumber;
	private String receiveName;
	private String bankNumber;
	private String bankInfo;
	private boolean middleMoney;
	private String debit;
	private String credit;
	private String reveiveInfo;
	private String bank;
    private String payDate;

	public OrderFee() {
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "MONEY", nullable = false, scale = 3)
	@NotNull
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "DESCRIPTION", length = 200)
	@Size(max = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PAY", nullable = false)
	public boolean isPay() {
		return this.pay;
	}

	public void setPay(boolean pay) {
		this.pay = pay;
	}


    @ManyToOne(optional = false,fetch = FetchType.LAZY)
    @JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
    @NotNull
    public CustomerOrder getCustomerOrder() {
        return customerOrder;
    }

    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }

	@Column(name = "PAY_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "CHECK_NUMBER", length = 50)
	@Size(max = 50)
	public String getCheckNumber() {
		return this.checkNumber;
	}

	public void setCheckNumber(String checkNumber) {
		this.checkNumber = checkNumber;
	}

	@Column(name = "RECEIVE_NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getReceiveName() {
		return this.receiveName;
	}

	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	@Column(name = "BANK_NUMBER", length = 50)
	@Size(max = 50)
	public String getBankNumber() {
		return this.bankNumber;
	}

	public void setBankNumber(String bankNumber) {
		this.bankNumber = bankNumber;
	}

	@Column(name = "BANK_INFO", length = 100)
	@Size(max = 100)
	public String getBankInfo() {
		return this.bankInfo;
	}

	public void setBankInfo(String bankInfo) {
		this.bankInfo = bankInfo;
	}

	@Column(name = "MIDDLE_MONEY", nullable = false)
	public boolean isMiddleMoney() {
		return this.middleMoney;
	}

	public void setMiddleMoney(boolean middleMoney) {
		this.middleMoney = middleMoney;
	}

	@Column(name = "DEBIT", length = 32)
	@Size(max = 32)
	public String getDebit() {
		return this.debit;
	}

	public void setDebit(String debit) {
		this.debit = debit;
	}

	@Column(name = "CREDIT", length = 32)
	@Size(max = 32)
	public String getCredit() {
		return this.credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}

	@Column(name = "REVEIVE_INFO", length = 300)
	@Size(max = 300)
	public String getReveiveInfo() {
		return this.reveiveInfo;
	}

	public void setReveiveInfo(String reveiveInfo) {
		this.reveiveInfo = reveiveInfo;
	}

	@Column(name = "BANK", length = 32)
	@Size(max = 32)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PAY_DATE", length = 19)
    public String getPayDate() {
        return payDate;
    }

    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }
}
