package com.dgsoft.erp.model;
// Generated Oct 28, 2013 12:46:39 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderDelivery generated by hbm2java
 */
@Entity
@Table(name = "ORDER_DELIVERY", catalog = "MINI_ERP")
public class OrderDelivery implements java.io.Serializable {

	private String id;
	private ExpressInfo expressInfo;
	private ProductToDoor productToDoor;
	private ExpressCar expressCar;
	private String deliveryType;
	private Date sendTime;
	private String memo;
	private BigDecimal money;
	private Set<Dispatch> dispatches = new HashSet<Dispatch>(0);

	public OrderDelivery() {
	}

	public OrderDelivery(String id, ExpressInfo expressInfo,
			ProductToDoor productToDoor, ExpressCar expressCar,
			String deliveryType, Date sendTime, BigDecimal money) {
		this.id = id;
		this.expressInfo = expressInfo;
		this.productToDoor = productToDoor;
		this.expressCar = expressCar;
		this.deliveryType = deliveryType;
		this.sendTime = sendTime;
		this.money = money;
	}
	public OrderDelivery(String id, ExpressInfo expressInfo,
			ProductToDoor productToDoor, ExpressCar expressCar,
			String deliveryType, Date sendTime, String memo, BigDecimal money,
			Set<Dispatch> dispatches) {
		this.id = id;
		this.expressInfo = expressInfo;
		this.productToDoor = productToDoor;
		this.expressCar = expressCar;
		this.deliveryType = deliveryType;
		this.sendTime = sendTime;
		this.memo = memo;
		this.money = money;
		this.dispatches = dispatches;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPRESS_INFO", nullable = false)
	@NotNull
	public ExpressInfo getExpressInfo() {
		return this.expressInfo;
	}

	public void setExpressInfo(ExpressInfo expressInfo) {
		this.expressInfo = expressInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_TO_DOOR", nullable = false)
	@NotNull
	public ProductToDoor getProductToDoor() {
		return this.productToDoor;
	}

	public void setProductToDoor(ProductToDoor productToDoor) {
		this.productToDoor = productToDoor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPRESS_CAR", nullable = false)
	@NotNull
	public ExpressCar getExpressCar() {
		return this.expressCar;
	}

	public void setExpressCar(ExpressCar expressCar) {
		this.expressCar = expressCar;
	}

	@Column(name = "DELIVERY_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SEND_TIME", nullable = false, length = 19)
	@NotNull
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "MONEY", nullable = false, scale = 3)
	@NotNull
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderDelivery")
	public Set<Dispatch> getDispatches() {
		return this.dispatches;
	}

	public void setDispatches(Set<Dispatch> dispatches) {
		this.dispatches = dispatches;
	}

}
