package com.dgsoft.erp.model;
// Generated Oct 30, 2013 3:06:10 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "ORDER_ITEM", catalog = "MINI_ERP")
public class OrderItem implements java.io.Serializable {

	private String id;
	private StoreRes storeRes;
	private UnitGroup unitGroup;
	private NeedRes needRes;
	private BigDecimal count;
	private BigDecimal cost;
	private BigDecimal money;
	private BigDecimal rebate;
	private BigDecimal middleMoney;
	private BigDecimal middleRate;
	private Set<DispatchItem> dispatchItems = new HashSet<DispatchItem>(0);

	public OrderItem() {
	}

	public OrderItem(String id, StoreRes storeRes, UnitGroup unitGroup,
			NeedRes needRes, BigDecimal count, BigDecimal cost,
			BigDecimal money, BigDecimal rebate, BigDecimal middleMoney,
			BigDecimal middleRate) {
		this.id = id;
		this.storeRes = storeRes;
		this.unitGroup = unitGroup;
		this.needRes = needRes;
		this.count = count;
		this.cost = cost;
		this.money = money;
		this.rebate = rebate;
		this.middleMoney = middleMoney;
		this.middleRate = middleRate;
	}
	public OrderItem(String id, StoreRes storeRes, UnitGroup unitGroup,
			NeedRes needRes, BigDecimal count, BigDecimal cost,
			BigDecimal money, BigDecimal rebate, BigDecimal middleMoney,
			BigDecimal middleRate, Set<DispatchItem> dispatchItems) {
		this.id = id;
		this.storeRes = storeRes;
		this.unitGroup = unitGroup;
		this.needRes = needRes;
		this.count = count;
		this.cost = cost;
		this.money = money;
		this.rebate = rebate;
		this.middleMoney = middleMoney;
		this.middleRate = middleRate;
		this.dispatchItems = dispatchItems;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_RES", nullable = false)
	@NotNull
	public StoreRes getStoreRes() {
		return this.storeRes;
	}

	public void setStoreRes(StoreRes storeRes) {
		this.storeRes = storeRes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MIDDLE_UNIT", nullable = false)
	@NotNull
	public UnitGroup getUnitGroup() {
		return this.unitGroup;
	}

	public void setUnitGroup(UnitGroup unitGroup) {
		this.unitGroup = unitGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NEED_RES", nullable = false)
	@NotNull
	public NeedRes getNeedRes() {
		return this.needRes;
	}

	public void setNeedRes(NeedRes needRes) {
		this.needRes = needRes;
	}

	@Column(name = "COUNT", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	@Column(name = "COST", nullable = false, scale = 3)
	@NotNull
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "MONEY", nullable = false, scale = 3)
	@NotNull
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "REBATE", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getRebate() {
		return this.rebate;
	}

	public void setRebate(BigDecimal rebate) {
		this.rebate = rebate;
	}

	@Column(name = "MIDDLE_MONEY", nullable = false, scale = 3)
	@NotNull
	public BigDecimal getMiddleMoney() {
		return this.middleMoney;
	}

	public void setMiddleMoney(BigDecimal middleMoney) {
		this.middleMoney = middleMoney;
	}

	@Column(name = "MIDDLE_RATE", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getMiddleRate() {
		return this.middleRate;
	}

	public void setMiddleRate(BigDecimal middleRate) {
		this.middleRate = middleRate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderItem")
	public Set<DispatchItem> getDispatchItems() {
		return this.dispatchItems;
	}

	public void setDispatchItems(Set<DispatchItem> dispatchItems) {
		this.dispatchItems = dispatchItems;
	}

}
