package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OrderList generated by hbm2java
 */
@Entity
@Table(name = "ORDER_LIST", catalog = "MINI_ERP")
public class OrderList implements java.io.Serializable {

	private String id;
	private StoreRes storeRes;
	private CustomerOrder customerOrder;
	private BigDecimal count;
	private BigDecimal cost;

	public OrderList() {
	}

	public OrderList(String id, StoreRes storeRes, CustomerOrder customerOrder,
			BigDecimal count) {
		this.id = id;
		this.storeRes = storeRes;
		this.customerOrder = customerOrder;
		this.count = count;
	}
	public OrderList(String id, StoreRes storeRes, CustomerOrder customerOrder,
			BigDecimal count, BigDecimal cost) {
		this.id = id;
		this.storeRes = storeRes;
		this.customerOrder = customerOrder;
		this.count = count;
		this.cost = cost;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RES", nullable = false)
	@NotNull
	public StoreRes getStoreRes() {
		return this.storeRes;
	}

	public void setStoreRes(StoreRes storeRes) {
		this.storeRes = storeRes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ORDER", nullable = false)
	@NotNull
	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	@Column(name = "COUNT", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	@Column(name = "COST", scale = 3)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

}
