package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ProductStoreIn generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_STORE_IN", catalog = "MINI_ERP")
public class ProductStoreIn implements java.io.Serializable {

	private String id;
	private Batch batch;
	private StockChange stockChange;

	public ProductStoreIn() {
	}

	public ProductStoreIn(String id, Batch batch, StockChange stockChange) {
		this.id = id;
		this.batch = batch;
		this.stockChange = stockChange;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BATCH", nullable = false)
	@NotNull
	public Batch getBatch() {
		return this.batch;
	}

	public void setBatch(Batch batch) {
		this.batch = batch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_CHANGE", nullable = false)
	@NotNull
	public StockChange getStockChange() {
		return this.stockChange;
	}

	public void setStockChange(StockChange stockChange) {
		this.stockChange = stockChange;
	}

}
