package com.dgsoft.erp.model;
// Generated Oct 30, 2013 1:46:18 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.GenericGenerator;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ProductToDoor generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_TO_DOOR", catalog = "MINI_ERP")
public class ProductToDoor implements java.io.Serializable {

	private String id;
    private String employeeId;
	private Cars cars;

	private Dispatch dispatch;

	public ProductToDoor() {
	}

    public ProductToDoor(Dispatch dispatch ,Cars cars){
        this.dispatch= dispatch;
        this.cars = cars;
    }

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAR", nullable = false)
	@NotNull
	public Cars getCars() {
		return this.cars;
	}

	public void setCars(Cars cars) {
		this.cars = cars;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "productToDoor")
	public Dispatch getDispatch() {
		return this.dispatch;
	}

	public void setDispatch(Dispatch dispatches) {
		this.dispatch = dispatches;
	}

    @Column(name = "EMP_DRIVER", nullable = true, length = 32)
    @Size(max = 32)
    public String getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

}
