package com.dgsoft.erp.model;
// Generated Sep 25, 2013 4:34:50 PM by Hibernate Tools 4.0.0

import com.dgsoft.common.OrderBeanComparator;
import org.hibernate.annotations.GenericGenerator;

import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Res generated by hbm2java
 */
@Entity
@Table(name = "RES", catalog = "MINI_ERP")
public class Res implements java.io.Serializable {

	private String id;
	private ResCategory resCategory;
	private String name;
	private String description;
    private String code;
	private boolean enable;
	private Set<StoreRes> storeReses = new HashSet<StoreRes>(0);
	private Set<FormatDefine> formatDefines = new HashSet<FormatDefine>(0);

    private ResUnit resUnitByInDefault;
    private ResUnit resUnitByMasterUnit;
    private ResUnit resUnitByOutDefault;

    private UnitGroup unitGroup;

	public Res() {
	}

    public Res(boolean enable) {
        this.enable = enable;
    }

	public Res(String id, ResCategory resCategory, String name, boolean enable) {
		this.id = id;
		this.resCategory = resCategory;
		this.name = name;
		this.enable = enable;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IN_DEFAULT", nullable = false)
    @NotNull
    public ResUnit getResUnitByInDefault() {
        return this.resUnitByInDefault;
    }

    public void setResUnitByInDefault(ResUnit resUnitByInDefault) {
        this.resUnitByInDefault = resUnitByInDefault;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MASTER_UNIT", nullable = false)
    @NotNull
    public ResUnit getResUnitByMasterUnit() {
        return this.resUnitByMasterUnit;
    }

    public void setResUnitByMasterUnit(ResUnit resUnitByMasterUnit) {
        this.resUnitByMasterUnit = resUnitByMasterUnit;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OUT_DEFAULT", nullable = false)
    @NotNull
    public ResUnit getResUnitByOutDefault() {
        return this.resUnitByOutDefault;
    }

    public void setResUnitByOutDefault(ResUnit resUnitByOutDefault) {
        this.resUnitByOutDefault = resUnitByOutDefault;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UNIT_GROUP", nullable = false)
    @NotNull
    public UnitGroup getUnitGroup() {
        return this.unitGroup;
    }

    public void setUnitGroup(UnitGroup unitGroup) {
        this.unitGroup = unitGroup;
    }


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY", nullable = false)
	@NotNull
	public ResCategory getResCategory() {
		return this.resCategory;
	}

	public void setResCategory(ResCategory resCategory) {
		this.resCategory = resCategory;
	}

    @Column(name = "CODE", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 200)
	@Size(max = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ENABLE", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "res")
	public Set<StoreRes> getStoreReses() {
		return this.storeReses;
	}

	public void setStoreReses(Set<StoreRes> storeReses) {
		this.storeReses = storeReses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "res", orphanRemoval = true, cascade = {CascadeType.ALL})
	public Set<FormatDefine> getFormatDefines() {
		return this.formatDefines;
	}

	public void setFormatDefines(Set<FormatDefine> formatDefines) {
		this.formatDefines = formatDefines;
	}

    @Transient
    public List<FormatDefine> getFormatDefineList(){
        List<FormatDefine> result = new ArrayList<FormatDefine>(getFormatDefines());
        Collections.sort(result, OrderBeanComparator.getInstance());
        return result;
    }

}
