package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ResCheck generated by hbm2java
 */
@Entity
@Table(name = "RES_CHECK", catalog = "MINI_ERP")
public class ResCheck implements java.io.Serializable {

	private String id;
	private Store store;
	private StoreChange storeChangeByLossRes;
	private StoreChange storeChangeByAddRes;
	private Date checkDate;
	private String memo;

	public ResCheck() {
	}

	public ResCheck(String id, Store store, Date checkDate) {
		this.id = id;
		this.store = store;
		this.checkDate = checkDate;
	}
	public ResCheck(String id, Store store, StoreChange storeChangeByLossRes,
			StoreChange storeChangeByAddRes, Date checkDate, String memo) {
		this.id = id;
		this.store = store;
		this.storeChangeByLossRes = storeChangeByLossRes;
		this.storeChangeByAddRes = storeChangeByAddRes;
		this.checkDate = checkDate;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE", nullable = false)
	@NotNull
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOSS_RES")
	public StoreChange getStoreChangeByLossRes() {
		return this.storeChangeByLossRes;
	}

	public void setStoreChangeByLossRes(StoreChange storeChangeByLossRes) {
		this.storeChangeByLossRes = storeChangeByLossRes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADD_RES")
	public StoreChange getStoreChangeByAddRes() {
		return this.storeChangeByAddRes;
	}

	public void setStoreChangeByAddRes(StoreChange storeChangeByAddRes) {
		this.storeChangeByAddRes = storeChangeByAddRes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHECK_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
