package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ResUnit generated by hbm2java
 */
@Entity
@Table(name = "RES_UNIT", catalog = "MINI_ERP")
public class ResUnit implements java.io.Serializable {

	private String id;
	private UnitGroup unitGroup;
	private String name;
	private BigDecimal conversionRate;
	private int priority;
	private Set<Res> resesForOutDefault = new HashSet<Res>(0);
	private Set<Res> resesForMasterUnit = new HashSet<Res>(0);
	private Set<Res> resesForInDefault = new HashSet<Res>(0);

	public ResUnit() {
	}

	public ResUnit(String id, UnitGroup unitGroup, String name, int priority) {
		this.id = id;
		this.unitGroup = unitGroup;
		this.name = name;
		this.priority = priority;
	}
	public ResUnit(String id, UnitGroup unitGroup, String name,
			BigDecimal conversionRate, int priority,
			Set<Res> resesForOutDefault, Set<Res> resesForMasterUnit,
			Set<Res> resesForInDefault) {
		this.id = id;
		this.unitGroup = unitGroup;
		this.name = name;
		this.conversionRate = conversionRate;
		this.priority = priority;
		this.resesForOutDefault = resesForOutDefault;
		this.resesForMasterUnit = resesForMasterUnit;
		this.resesForInDefault = resesForInDefault;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIT_GROUP", nullable = false)
	@NotNull
	public UnitGroup getUnitGroup() {
		return this.unitGroup;
	}

	public void setUnitGroup(UnitGroup unitGroup) {
		this.unitGroup = unitGroup;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CONVERSION_RATE", scale = 10)
	public BigDecimal getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(BigDecimal conversionRate) {
		this.conversionRate = conversionRate;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resUnitByOutDefault")
	public Set<Res> getResesForOutDefault() {
		return this.resesForOutDefault;
	}

	public void setResesForOutDefault(Set<Res> resesForOutDefault) {
		this.resesForOutDefault = resesForOutDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resUnitByMasterUnit")
	public Set<Res> getResesForMasterUnit() {
		return this.resesForMasterUnit;
	}

	public void setResesForMasterUnit(Set<Res> resesForMasterUnit) {
		this.resesForMasterUnit = resesForMasterUnit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resUnitByInDefault")
	public Set<Res> getResesForInDefault() {
		return this.resesForInDefault;
	}

	public void setResesForInDefault(Set<Res> resesForInDefault) {
		this.resesForInDefault = resesForInDefault;
	}

}
