package com.dgsoft.erp.model;
// Generated Oct 20, 2013 6:30:11 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * StoreBorrow generated by hbm2java
 */
@Entity
@Table(name = "STORE_BORROW", catalog = "MINI_ERP")
public class StoreBorrow implements java.io.Serializable {

	private String id;
	private StockChange stockChangeByStoreIn;
	private StockChange stockChangeByStoreOut;
	private String type;
	private Date createDate;
	private Date completeDate;
	private Date limitDate;
	private String state;
	private String borrowTarget;
	private String memo;

	public StoreBorrow() {
	}

	public StoreBorrow(String id, StockChange stockChangeByStoreIn,
			StockChange stockChangeByStoreOut, String type, Date createDate,
			Date completeDate, Date limitDate, String state, String borrowTarget) {
		this.id = id;
		this.stockChangeByStoreIn = stockChangeByStoreIn;
		this.stockChangeByStoreOut = stockChangeByStoreOut;
		this.type = type;
		this.createDate = createDate;
		this.completeDate = completeDate;
		this.limitDate = limitDate;
		this.state = state;
		this.borrowTarget = borrowTarget;
	}
	public StoreBorrow(String id, StockChange stockChangeByStoreIn,
			StockChange stockChangeByStoreOut, String type, Date createDate,
			Date completeDate, Date limitDate, String state,
			String borrowTarget, String memo) {
		this.id = id;
		this.stockChangeByStoreIn = stockChangeByStoreIn;
		this.stockChangeByStoreOut = stockChangeByStoreOut;
		this.type = type;
		this.createDate = createDate;
		this.completeDate = completeDate;
		this.limitDate = limitDate;
		this.state = state;
		this.borrowTarget = borrowTarget;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_IN", nullable = false)
	@NotNull
	public StockChange getStockChangeByStoreIn() {
		return this.stockChangeByStoreIn;
	}

	public void setStockChangeByStoreIn(StockChange stockChangeByStoreIn) {
		this.stockChangeByStoreIn = stockChangeByStoreIn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_OUT", nullable = false)
	@NotNull
	public StockChange getStockChangeByStoreOut() {
		return this.stockChangeByStoreOut;
	}

	public void setStockChangeByStoreOut(StockChange stockChangeByStoreOut) {
		this.stockChangeByStoreOut = stockChangeByStoreOut;
	}

	@Column(name = "TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMPLETE_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCompleteDate() {
		return this.completeDate;
	}

	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LIMIT_DATE", nullable = false, length = 19)
	@NotNull
	public Date getLimitDate() {
		return this.limitDate;
	}

	public void setLimitDate(Date limitDate) {
		this.limitDate = limitDate;
	}

	@Column(name = "STATE", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "BORROW_TARGET", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getBorrowTarget() {
		return this.borrowTarget;
	}

	public void setBorrowTarget(String borrowTarget) {
		this.borrowTarget = borrowTarget;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
