package com.dgsoft.erp.model;
// Generated Oct 1, 2013 5:41:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * StoreOut generated by hbm2java
 */
@Entity
@Table(name = "STORE_OUT", catalog = "MINI_ERP")
public class StoreOut implements java.io.Serializable {

	private String id;
	private StoreChange storeChange;
	private String reason;
	private Set<OrderDelivery> orderDeliveries = new HashSet<OrderDelivery>(0);

	public StoreOut() {
	}

	public StoreOut(String id, StoreChange storeChange, String reason) {
		this.id = id;
		this.storeChange = storeChange;
		this.reason = reason;
	}
	public StoreOut(String id, StoreChange storeChange, String reason,
			Set<OrderDelivery> orderDeliveries) {
		this.id = id;
		this.storeChange = storeChange;
		this.reason = reason;
		this.orderDeliveries = orderDeliveries;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_CHANGE", nullable = false)
	@NotNull
	public StoreChange getStoreChange() {
		return this.storeChange;
	}

	public void setStoreChange(StoreChange storeChange) {
		this.storeChange = storeChange;
	}

	@Column(name = "REASON", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeOut")
	public Set<OrderDelivery> getOrderDeliveries() {
		return this.orderDeliveries;
	}

	public void setOrderDeliveries(Set<OrderDelivery> orderDeliveries) {
		this.orderDeliveries = orderDeliveries;
	}

}
