package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "SUPPLIER", catalog = "MINI_ERP")
public class Supplier implements java.io.Serializable {

	private String id;
	private String name;
	private Set<Batch> batches = new HashSet<Batch>(0);
	private Set<SupplierRes> supplierReses = new HashSet<SupplierRes>(0);

	public Supplier() {
	}

	public Supplier(String id, String name) {
		this.id = id;
		this.name = name;
	}
	public Supplier(String id, String name, Set<Batch> batches,
			Set<SupplierRes> supplierReses) {
		this.id = id;
		this.name = name;
		this.batches = batches;
		this.supplierReses = supplierReses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Batch> getBatches() {
		return this.batches;
	}

	public void setBatches(Set<Batch> batches) {
		this.batches = batches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<SupplierRes> getSupplierReses() {
		return this.supplierReses;
	}

	public void setSupplierReses(Set<SupplierRes> supplierReses) {
		this.supplierReses = supplierReses;
	}

}
