package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * SupplierRes generated by hbm2java
 */
@Entity
@Table(name = "SUPPLIER_RES", catalog = "MINI_ERP")
public class SupplierRes implements java.io.Serializable {

	private SupplierResId id;
	private StoreRes storeRes;
	private Supplier supplier;

	public SupplierRes() {
	}

	public SupplierRes(SupplierResId id, StoreRes storeRes, Supplier supplier) {
		this.id = id;
		this.storeRes = storeRes;
		this.supplier = supplier;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "supplier", column = @Column(name = "SUPPLIER", nullable = false, length = 32)),
			@AttributeOverride(name = "storeRes", column = @Column(name = "STORE_RES", nullable = false, length = 32))})
	@NotNull
	public SupplierResId getId() {
		return this.id;
	}

	public void setId(SupplierResId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_RES", nullable = false, insertable = false, updatable = false)
	@NotNull
	public StoreRes getStoreRes() {
		return this.storeRes;
	}

	public void setStoreRes(StoreRes storeRes) {
		this.storeRes = storeRes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUPPLIER", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

}
