package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * TransCorp generated by hbm2java
 */
@Entity
@Table(name = "TRANS_CORP", catalog = "MINI_ERP")
public class TransCorp implements java.io.Serializable {

	private String id;
	private String name;
	private String tel;
	private String contact;
	private boolean enable;
	private Set<ExpressInfo> expressInfos = new HashSet<ExpressInfo>(0);

	public TransCorp() {
	}

	public TransCorp(String id, String name, boolean enable) {
		this.id = id;
		this.name = name;
		this.enable = enable;
	}
	public TransCorp(String id, String name, String tel, String contact,
			boolean enable, Set<ExpressInfo> expressInfos) {
		this.id = id;
		this.name = name;
		this.tel = tel;
		this.contact = contact;
		this.enable = enable;
		this.expressInfos = expressInfos;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TEL", length = 50)
	@Size(max = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "CONTACT", length = 50)
	@Size(max = 50)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "ENABLE", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transCorp")
	public Set<ExpressInfo> getExpressInfos() {
		return this.expressInfos;
	}

	public void setExpressInfos(Set<ExpressInfo> expressInfos) {
		this.expressInfos = expressInfos;
	}

}
