package com.dgsoft.erp.model;
// Generated Oct 17, 2013 5:33:51 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * UnitGroup generated by hbm2java
 */
@Entity
@Table(name = "UNIT_GROUP", catalog = "MINI_ERP")
public class UnitGroup implements java.io.Serializable {

	private String id;
	private String name;
	private String type;
	private Set<Res> reses = new HashSet<Res>(0);
	private Set<ResUnit> resUnits = new HashSet<ResUnit>(0);

	public UnitGroup() {
	}

	public UnitGroup(String id, String name, String type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}
	public UnitGroup(String id, String name, String type, Set<Res> reses,
			Set<ResUnit> resUnits) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.reses = reses;
		this.resUnits = resUnits;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitGroup")
	public Set<Res> getReses() {
		return this.reses;
	}

	public void setReses(Set<Res> reses) {
		this.reses = reses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitGroup")
	public Set<ResUnit> getResUnits() {
		return this.resUnits;
	}

	public void setResUnits(Set<ResUnit> resUnits) {
		this.resUnits = resUnits;
	}

}
