SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX RELATIONSHIP_6_FK ON DG_SYSTEM.EMPLOYEE;
DROP INDEX RELATIONSHIP_11_FK ON DG_SYSTEM.WORD;



/* Drop Tables */

DROP TABLE DG_SYSTEM.REPORT_REPROT_SUBSCRIBE;
DROP TABLE DG_SYSTEM.REPORT;
DROP TABLE DG_SYSTEM.ROLE_FUNCTION;
DROP TABLE DG_SYSTEM.FUNCTION;
DROP TABLE DG_SYSTEM.FUNC_CATEGORY;
DROP TABLE DG_SYSTEM.BUSINESS_TASK;
DROP TABLE DG_SYSTEM.BUSINESS_INSTANCE;
DROP TABLE DG_SYSTEM.SYSTEM_LOG;
DROP TABLE DG_SYSTEM.ROLE_EMP;
DROP TABLE DG_SYSTEM.EMPLOYEE;
DROP TABLE DG_SYSTEM.ORGANIZATION;
DROP TABLE DG_SYSTEM.RATE_RATE_SUBSCRIBE;
DROP TABLE DG_SYSTEM.RATE;
DROP TABLE DG_SYSTEM.FILE_SUBSCRIBE;
DROP TABLE DG_SYSTEM.COMPLEX_VAR_SUBSCRIBE;
DROP TABLE DG_SYSTEM.RATE_SUBSCRIBE;
DROP TABLE DG_SYSTEM.REPORT_SUBSCRIBE;
DROP TABLE DG_SYSTEM.SIMPLE_VAR_SUBSCRIBE;
DROP TABLE DG_SYSTEM.SIMPLE_VAR_DEFINE;
DROP TABLE DG_SYSTEM.PERSON;
DROP TABLE DG_SYSTEM.ROLE_BIZ;
DROP TABLE DG_SYSTEM.CITY;
DROP TABLE DG_SYSTEM.ROLE;
DROP TABLE DG_SYSTEM.BUSINESS_DEFINE;
DROP TABLE DG_SYSTEM.BUSINESS_CATEGORY;
DROP TABLE DG_SYSTEM.PROVINCE;
DROP TABLE DG_SYSTEM.WORD;
DROP TABLE DG_SYSTEM.WORD_CATEGORY;
DROP TABLE DG_SYSTEM.SYSTEM_PARAM;
DROP TABLE DG_SYSTEM.NUMBER_POOL;




/* Create Tables */

CREATE TABLE DG_SYSTEM.REPORT
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) COMMENT 'NAME',
	NESTING BIT(1) NOT NULL COMMENT '是否套打',
	LOCATION VARCHAR(100) COMMENT '报表位置',
	NESTING_LOCATION VARCHAR(100) COMMENT '套打位置',
	VERSION INT COMMENT '报表版本',
	PRIORITY INT NOT NULL COMMENT '优先级',
	MEMO VARCHAR(200) COMMENT 'MEMO',
	CONSTRAINT PK_DGREPORTITEMS PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'REPORT' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.FUNC_CATEGORY
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	ICON VARCHAR(100) COMMENT 'ICON',
	PRIORITY INT NOT NULL COMMENT '优先级',
	MEMO VARCHAR(100) COMMENT 'MEMO',
	CONSTRAINT PK_DGFUNCGROUP PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '功能种类' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.FUNCTION
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(20) NOT NULL COMMENT 'NAME',
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'CATEGORY',
	ICON VARCHAR(100) NOT NULL COMMENT 'ICON',
	LOCATION VARCHAR(100) NOT NULL COMMENT '请求位置',
	-- 功能页head上的图片
	BANNER VARCHAR(100) COMMENT 'BANNER',
	PRIORITY INT NOT NULL COMMENT '优先级',
	MEMO VARCHAR(100) COMMENT 'MEMO',
	CONSTRAINT PK_DGFUNCTION PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '功能' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.ORGANIZATION
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	PARENT VARCHAR(32) COMMENT '上层组织',
	ROOT BIT(1) NOT NULL COMMENT '根',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	PHONE_NUMBER VARCHAR(20) COMMENT '电话',
	MEMO VARCHAR(100) COMMENT 'MEMO',
	CONSTRAINT PK_DGORGANISE PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '组织机构' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.RATE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	RATE_RULE VARCHAR(500) NOT NULL COMMENT '计算费用公式',
	DETAILS_RULE VARCHAR(500) COMMENT '计算方法公式',
	PRIORITY INT NOT NULL COMMENT '优先级',
	MEMO VARCHAR(200) COMMENT 'MEMO',
	CONSTRAINT PK_DGRATEITEMS PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '收费计算公式' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.RATE_RATE_SUBSCRIBE
(
	SUB_ID VARCHAR(32) NOT NULL COMMENT 'SUB_ID',
	RATE_ID VARCHAR(32) NOT NULL COMMENT 'RATE_ID',
	PRIMARY KEY (SUB_ID, RATE_ID)
) ENGINE = InnoDB COMMENT = '收费订阅关联' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.FILE_SUBSCRIBE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	-- 文件类型
	TYPE INT NOT NULL COMMENT 'TYPE',
	IMPORTANT BIT(1) NOT NULL COMMENT '要件',
	WF_TASK VARCHAR(32) NOT NULL COMMENT '工作流阶段',
	WF_VER VARCHAR(32) NOT NULL COMMENT '工作流版本',
	BUSINESS_DEFINE VARCHAR(32) NOT NULL COMMENT 'BUSINESS_DEFINE',
	PRIORITY INT NOT NULL COMMENT '优先级',
	CONSTRAINT PK_DGBIZDOC PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '业务要件/附件订阅' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.SYSTEM_LOG
(
	ID INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
	DATE TIMESTAMP COMMENT 'DATE',
	THREAD VARCHAR(50) COMMENT 'THREAD',
	LEVEL VARCHAR(10) COMMENT 'LEVEL',
	EMPLOYEE VARCHAR(32) COMMENT 'EMPLOYEE',
	CLASS VARCHAR(100) COMMENT 'CLASS',
	MESSAGES VARCHAR(100) COMMENT 'MESSAGES',
	CONSTRAINT PK_DGSYSTEMLOG PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '日志' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.REPORT_REPROT_SUBSCRIBE
(
	REP_ID VARCHAR(32) NOT NULL COMMENT 'REP_ID',
	REP_SUB_ID VARCHAR(32) NOT NULL COMMENT 'REP_SUB_ID',
	PRIMARY KEY (REP_ID, REP_SUB_ID)
) ENGINE = InnoDB COMMENT = '报表订阅关联表' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.COMPLEX_VAR_SUBSCRIBE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	WF_TASK VARCHAR(32) NOT NULL COMMENT '工作流阶段',
	WF_VER VARCHAR(32) NOT NULL COMMENT '工作流版本',
	BUSINESS_DEFIN VARCHAR(32) NOT NULL COMMENT 'BUSINESS_DEFIN',
	TITLE VARCHAR(50) NOT NULL COMMENT 'TITLE',
	VIEW_LOCATION VARCHAR(200) NOT NULL COMMENT '视图定位',
	COMPONENT_NAME VARCHAR(100) NOT NULL COMMENT '处理组件名',
	PRIORITY INT NOT NULL COMMENT '优先级',
	REQUEST BIT(1) NOT NULL COMMENT '必填',
	READONLY BIT(1) NOT NULL COMMENT '只读',
	PRIMARY KEY (ID),
	CONSTRAINT COMPLEX_SUBSCRIBE_UNIQUE UNIQUE (WF_TASK, WF_VER, BUSINESS_DEFIN, VIEW_LOCATION, COMPONENT_NAME)
) ENGINE = InnoDB COMMENT = '复杂变量订阅' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.RATE_SUBSCRIBE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	WF_TASK VARCHAR(32) NOT NULL COMMENT '工作流阶段',
	WF_VER VARCHAR(32) NOT NULL COMMENT '工作流版本',
	BUSINESS_DEFINE VARCHAR(32) NOT NULL COMMENT 'BUSINESS_DEFINE',
	PRIORITY INT NOT NULL COMMENT '优先级',
	CONSTRAINT PK_DGBIZANDRATEITEMS PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '收费订阅' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.REPORT_SUBSCRIBE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	WF_VER VARCHAR(32) NOT NULL COMMENT '工作流版本',
	WF_TASK VARCHAR(32) NOT NULL COMMENT '工作流阶段',
	BUSINESS_DEFINE VARCHAR(32) NOT NULL COMMENT 'BUSINESS_DEFINE',
	PRIORITY INT NOT NULL COMMENT '优先级',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '业务报表订阅' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.SIMPLE_VAR_SUBSCRIBE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	WF_TASK VARCHAR(32) NOT NULL COMMENT '工作流阶段',
	WF_VER VARCHAR(32) NOT NULL COMMENT '工作流版本',
	BUSINESS_DEFIN VARCHAR(32) NOT NULL COMMENT 'BUSINESS_DEFIN',
	VARIABLE VARCHAR(32) NOT NULL COMMENT 'VARIABLE',
	PRIORITY INT NOT NULL COMMENT '优先级',
	REQUEST BIT(1) NOT NULL COMMENT '是否必填',
	READONLY BIT(1) NOT NULL COMMENT '只读',
	-- 输入框尺寸
	SIZE INT COMMENT '尺寸',
	PRIMARY KEY (ID),
	CONSTRAINT SIMPLE_SUBSCRIBE_UNIQUE UNIQUE (WF_TASK, WF_VER, BUSINESS_DEFIN, VARIABLE)
) ENGINE = InnoDB COMMENT = '基本变量订阅' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.SIMPLE_VAR_DEFINE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	TITLE VARCHAR(50) NOT NULL COMMENT 'TITLE',
	LENGTH INT NOT NULL COMMENT 'LENGTH',
	TYPE VARCHAR(32) NOT NULL COMMENT 'TYPE',
	DESCRIPTION VARCHAR(200) COMMENT 'DESCRIPTION',
	WORD_TYPE VARCHAR(32) COMMENT 'WORD_TYPE',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'SIMPLE_VAR_DEFINE' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.PERSON
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	CREDENTIALS_TYPE VARCHAR(32) NOT NULL COMMENT '证件类型',
	CREDENTIALS_NUMBER VARCHAR(100) NOT NULL COMMENT '证件号',
	CREDENTIALS_ORGAN VARCHAR(100) COMMENT '发证机关',
	SEX VARCHAR(32) COMMENT '性别',
	ETHNIC VARCHAR(20) COMMENT '民族',
	DATE_OF_BIRTH DATETIME COMMENT '出生日期',
	-- 一般为身份证地址
	ADDRESS VARCHAR(200) COMMENT '地址',
	NOW_ADDRESS VARCHAR(200) COMMENT '居住地址',
	NATIONALITY VARCHAR(100) COMMENT '国籍',
	PHONE VARCHAR(50) COMMENT '电话',
	CITY VARCHAR(50) COMMENT '户口所在地',
	_FOREIGN BIT(1) NOT NULL COMMENT '外籍人',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '自然人' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.EMPLOYEE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORGANIZATION VARCHAR(32) COMMENT '组织机构',
	JOIN_DATE DATETIME COMMENT '入职时间',
	E_MAIL VARCHAR(20) COMMENT 'E_Mail',
	PASSWORD VARCHAR(100) COMMENT 'PASSWORD',
	ENABLE BIT(1) NOT NULL COMMENT '启用',
	JOB VARCHAR(32) COMMENT '岗位',
	PERSON_ID VARCHAR(32) NOT NULL COMMENT 'PERSON_ID',
	MEMO VARCHAR(100) COMMENT 'MEMO',
	CONSTRAINT PK_DGEMPLOYEE PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '员工' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.BUSINESS_TASK
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	BEGIN_TIME DATETIME NOT NULL COMMENT '任务到达时间',
	COMPLETE_TIME DATETIME NOT NULL COMMENT '完成时间',
	BUSSINESS_INSTNACE_ID VARCHAR(32) NOT NULL COMMENT '业务',
	EMPLOYEE_ID VARCHAR(32) NOT NULL COMMENT 'EMPLOYEE_ID',
	STAGE VARCHAR(100) NOT NULL COMMENT '阶段',
	STAGE_ID VARCHAR(32) NOT NULL COMMENT '阶段ID',
	FALLBACK_OPER BIT(1) NOT NULL COMMENT '回退处理',
	ERROR_OPER BIT(1) NOT NULL COMMENT '错误处理',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '业务任务表' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.BUSINESS_INSTANCE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	CREATE_TIME DATETIME NOT NULL COMMENT '建立时间',
	COMPLETE_TIME DATETIME COMMENT '完成时间',
	MARK VARCHAR(200) COMMENT '标识',
	STATE VARCHAR(32) NOT NULL COMMENT 'STATE',
	BUSINESS_DEFINE_ID VARCHAR(32) NOT NULL COMMENT 'BUSINESS_DEFINE_ID',
	PROCESS_MESSAGE VARCHAR(400) COMMENT '流程消息',
	CURRENT_OPER_EMPLOYEE_ID VARCHAR(32) NOT NULL COMMENT '业务发起人',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '业务实例' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.ROLE_BIZ
(
	ROLE_ID VARCHAR(32) NOT NULL COMMENT 'ROLE_ID',
	BIZ_ID VARCHAR(32) NOT NULL COMMENT 'BIZ_ID',
	CONSTRAINT PK_DGROLEBIZ PRIMARY KEY (ROLE_ID, BIZ_ID)
) ENGINE = InnoDB COMMENT = 'ROLE_BIZ' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.ROLE_EMP
(
	EMP_ID VARCHAR(32) NOT NULL COMMENT 'EMP_ID',
	ROL_ID VARCHAR(32) NOT NULL COMMENT 'ROL_ID',
	PRIMARY KEY (EMP_ID, ROL_ID)
) ENGINE = InnoDB COMMENT = 'ROLE_EMP' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.CITY
(
	PID INT NOT NULL COMMENT 'PID',
	NAME VARCHAR(50) COMMENT 'NAME',
	SORT INT COMMENT 'SORT',
	FID INT NOT NULL COMMENT 'FID',
	PRIMARY KEY (PID)
) ENGINE = InnoDB COMMENT = '市/自治区/自治州' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.ROLE_FUNCTION
(
	FUN_ID VARCHAR(32) NOT NULL COMMENT 'FUN_ID',
	ROL_ID VARCHAR(32) NOT NULL COMMENT 'ROL_ID',
	CONSTRAINT PK_DGROLEFUNCTION PRIMARY KEY (FUN_ID, ROL_ID)
) ENGINE = InnoDB COMMENT = 'ROLE_FUNCTION' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.ROLE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(20) NOT NULL COMMENT 'NAME',
	DESCRIPTION VARCHAR(200) COMMENT 'DESCRIPTION',
	PRIORITY INT NOT NULL COMMENT '优先级',
	CONSTRAINT PK_DGROLE PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '角色' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.BUSINESS_CATEGORY
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	PRIORITY INT NOT NULL COMMENT '优先级',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '业务种类' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.PROVINCE
(
	PID INT NOT NULL COMMENT 'PID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	SORT INT NOT NULL COMMENT 'SORT',
	PRIMARY KEY (PID)
) ENGINE = InnoDB COMMENT = '省/行政区' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.BUSINESS_DEFINE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	WF_NAME VARCHAR(32) NOT NULL COMMENT '工作流名称',
	START_PAGE VARCHAR(200) COMMENT '启动处理页面',
	START_DATA_VALIDATOR VARCHAR(100) COMMENT '启动数据验证器',
	TASK_SERVICE VARCHAR(100) COMMENT '业务处理组件名',
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'CATEGORY',
	MEMO VARCHAR(200) COMMENT 'MEMO',
	-- 乐观锁
	VERSION INT COMMENT 'VERSION',
	START_PROPAGATION VARCHAR(10) COMMENT '启动页propagation',
	CONSTRAINT PK_DGBIZ PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '业务种类' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.WORD_CATEGORY
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NAME VARCHAR(50) NOT NULL COMMENT 'NAME',
	MEMO VARCHAR(100) COMMENT 'MEMO',
	SYSTEM BIT(1) NOT NULL COMMENT 'SYSTEM',
	CONSTRAINT PK_DGWORDBOOKTYPE PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '字典种类' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.WORD
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	_KEY VARCHAR(50) NOT NULL COMMENT 'KEY',
	_VALUE VARCHAR(100) NOT NULL COMMENT 'VALUE',
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'CATEGORY',
	DESCRIPTION VARCHAR(200) COMMENT 'DESCRIPTION',
	PRIORITY INT NOT NULL COMMENT '优先级',
	ENABLE BIT(1) NOT NULL COMMENT '可用',
	CONSTRAINT PK_DGWORDBOOK PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '字典' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.SYSTEM_PARAM
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	TYPE VARCHAR(32) NOT NULL COMMENT 'TYPE',
	VALUE VARCHAR(100) NOT NULL COMMENT 'VALUE',
	MEMO VARCHAR(100) COMMENT 'MEMO',
	CONSTRAINT PK_DGSYSTEMPARAM PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '系统参数' DEFAULT CHARACTER SET utf8;


CREATE TABLE DG_SYSTEM.NUMBER_POOL
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	NUMBER BIGINT UNSIGNED NOT NULL COMMENT 'NUMBER',
	POOL_SIZE INT NOT NULL COMMENT 'POOL_SIZE',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '号池' DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE DG_SYSTEM.REPORT_REPROT_SUBSCRIBE
	ADD FOREIGN KEY (REP_ID)
	REFERENCES DG_SYSTEM.REPORT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.FUNCTION
	ADD CONSTRAINT FK_DGFUNCTI_REFERENCE_DGFUNCGR FOREIGN KEY (CATEGORY)
	REFERENCES DG_SYSTEM.FUNC_CATEGORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ROLE_FUNCTION
	ADD CONSTRAINT FK_DGROLEFU_RELATIONS_DGFUNCTI FOREIGN KEY (FUN_ID)
	REFERENCES DG_SYSTEM.FUNCTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.EMPLOYEE
	ADD CONSTRAINT FK_DGEMPLOY_RELATIONS_DGORGANI FOREIGN KEY (ORGANIZATION)
	REFERENCES DG_SYSTEM.ORGANIZATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ORGANIZATION
	ADD CONSTRAINT FK_DGORGANI_REFERENCE_DGORGANI FOREIGN KEY (PARENT)
	REFERENCES DG_SYSTEM.ORGANIZATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.RATE_RATE_SUBSCRIBE
	ADD FOREIGN KEY (RATE_ID)
	REFERENCES DG_SYSTEM.RATE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.RATE_RATE_SUBSCRIBE
	ADD FOREIGN KEY (SUB_ID)
	REFERENCES DG_SYSTEM.RATE_SUBSCRIBE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.REPORT_REPROT_SUBSCRIBE
	ADD FOREIGN KEY (REP_SUB_ID)
	REFERENCES DG_SYSTEM.REPORT_SUBSCRIBE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.SIMPLE_VAR_SUBSCRIBE
	ADD FOREIGN KEY (VARIABLE)
	REFERENCES DG_SYSTEM.SIMPLE_VAR_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.EMPLOYEE
	ADD FOREIGN KEY (PERSON_ID)
	REFERENCES DG_SYSTEM.PERSON (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.BUSINESS_INSTANCE
	ADD FOREIGN KEY (CURRENT_OPER_EMPLOYEE_ID)
	REFERENCES DG_SYSTEM.EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.SYSTEM_LOG
	ADD CONSTRAINT FK_DGSYSTEM_REFERENCE_DGEMPLOY FOREIGN KEY (EMPLOYEE)
	REFERENCES DG_SYSTEM.EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.BUSINESS_TASK
	ADD FOREIGN KEY (EMPLOYEE_ID)
	REFERENCES DG_SYSTEM.EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ROLE_EMP
	ADD FOREIGN KEY (EMP_ID)
	REFERENCES DG_SYSTEM.EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.BUSINESS_TASK
	ADD FOREIGN KEY (BUSSINESS_INSTNACE_ID)
	REFERENCES DG_SYSTEM.BUSINESS_INSTANCE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ROLE_BIZ
	ADD CONSTRAINT FK_DGROLEBI_REFERENCE_DGROLE FOREIGN KEY (ROLE_ID)
	REFERENCES DG_SYSTEM.ROLE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ROLE_FUNCTION
	ADD FOREIGN KEY (ROL_ID)
	REFERENCES DG_SYSTEM.ROLE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ROLE_EMP
	ADD FOREIGN KEY (ROL_ID)
	REFERENCES DG_SYSTEM.ROLE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.BUSINESS_DEFINE
	ADD FOREIGN KEY (CATEGORY)
	REFERENCES DG_SYSTEM.BUSINESS_CATEGORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.CITY
	ADD FOREIGN KEY (FID)
	REFERENCES DG_SYSTEM.PROVINCE (PID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.BUSINESS_INSTANCE
	ADD FOREIGN KEY (BUSINESS_DEFINE_ID)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.FILE_SUBSCRIBE
	ADD FOREIGN KEY (BUSINESS_DEFINE)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.SIMPLE_VAR_SUBSCRIBE
	ADD FOREIGN KEY (BUSINESS_DEFIN)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.RATE_SUBSCRIBE
	ADD CONSTRAINT FK_DGBIZAND_REFERENCE_DGBIZ FOREIGN KEY (BUSINESS_DEFINE)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.COMPLEX_VAR_SUBSCRIBE
	ADD FOREIGN KEY (BUSINESS_DEFIN)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.REPORT_SUBSCRIBE
	ADD FOREIGN KEY (BUSINESS_DEFINE)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.ROLE_BIZ
	ADD CONSTRAINT FK_DGROLEBI_REFERENCE_DGBIZ FOREIGN KEY (BIZ_ID)
	REFERENCES DG_SYSTEM.BUSINESS_DEFINE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.WORD
	ADD CONSTRAINT FK_DGWORDBO_RELATIONS_DGWORDBO FOREIGN KEY (CATEGORY)
	REFERENCES DG_SYSTEM.WORD_CATEGORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DG_SYSTEM.SIMPLE_VAR_DEFINE
	ADD FOREIGN KEY (WORD_TYPE)
	REFERENCES DG_SYSTEM.WORD_CATEGORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Indexes */

CREATE INDEX RELATIONSHIP_6_FK USING BTREE ON DG_SYSTEM.EMPLOYEE (ORGANIZATION ASC);
CREATE INDEX RELATIONSHIP_11_FK USING BTREE ON DG_SYSTEM.WORD (CATEGORY ASC);



