
/*MOVE STOCK SEARCH TO RESMGR */
UPDATE DG_SYSTEM.FUNCTION SET CATEGORY = 'erp.res.mgr', PRIORITY  = 20 WHERE ID = 'erp.store.stockSearch'
DELETE FROM DG_SYSTEM.FUNC_CATEGORY WHERE ID = 'erp.search'



