ALTER TABLE MINI_ERP.RES_SALE_REBATE ADD ITEM_REBATE DECIMAL(19,4) NOT NULL;

ALTER TABLE MINI_ERP.RES_SALE_REBATE DROP PRICE;




INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.sale.saler', 'system.processInstanceMgr');
UPDATE DG_SYSTEM.FUNCTION SET LOCATION = '/func/erp/finance/Accounting.seam' where ID ='finance.account';

INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.finance.cashier', 'finance.account');
UPDATE DG_SYSTEM.FUNCTION SET LOCATION = '/func/system/ProcessInstanceMgr.seam' where ID ='system.processInstanceMgr';


CREATE TABLE MINI_ERP.STOCK_ACCOUNT
(
  CHECKOUT BIGINT NOT NULL COMMENT 'CHECKOUT',
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  STOCK VARCHAR(32) NOT NULL COMMENT 'STOCK',
  BEGIN_COUNT DECIMAL(19,4) NOT NULL COMMENT 'BEGIN_COUNT',
  CLOSE_COUNT DECIMAL(19,4) NOT NULL COMMENT 'CLOSE_COUNT',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'STOCK_ACCOUNT' DEFAULT CHARACTER SET utf8;

ALTER TABLE MINI_ERP.STOCK_ACCOUNT
ADD FOREIGN KEY (STOCK)
REFERENCES MINI_ERP.STOCK (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;



ALTER TABLE MINI_ERP.STOCK_ACCOUNT
ADD FOREIGN KEY (CHECKOUT)
REFERENCES MINI_ERP.CHECK_OUT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;
