CREATE TABLE MINI_ERP.ORDER_OPER
(
	ORDER_ID VARCHAR(32) NOT NULL COMMENT 'ORDER_ID',
	OPER_ID VARCHAR(32) NOT NULL COMMENT 'OPER_ID',
	PRIMARY KEY (ORDER_ID, OPER_ID)
) ENGINE = InnoDB COMMENT = 'ORDER_OPER' DEFAULT CHARACTER SET utf8;

ALTER TABLE MINI_ERP.ORDER_OPER
	ADD FOREIGN KEY (ORDER_ID)
	REFERENCES MINI_ERP.CUSTOMER_ORDER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.ORDER_OPER
	ADD FOREIGN KEY (OPER_ID)
	REFERENCES MINI_ERP.ACCOUNT_OPER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



-- move to many to many