ALTER TABLE MINI_ERP.CUSTOMER ADD CITY VARCHAR(100) NOT NULL;

UPDATE MINI_ERP.CUSTOMER  LEFT JOIN DG_SYSTEM.CITY p on p.PID  = CUSTOMER.PROVINCE_CODE
SET CUSTOMER.CITY = p.NAME ;


UPDATE MINI_ERP.CUSTOMER  LEFT JOIN DG_SYSTEM.CITY p on p.PID  = CUSTOMER.PROVINCE_CODE
SET CUSTOMER.PROVINCE_CODE = p.FID;