ALTER TABLE MINI_ERP.ACCOUNT_OPER ADD REMIT_FEE DECIMAL(19,3) NOT NULL;

ALTER TABLE MINI_ERP.CUSTOMER_ORDER CHANGE CONTACT CONTACT varchar(50);
ALTER TABLE MINI_ERP.CUSTOMER_ORDER MODIFY COLUMN CONTACT varchar(50) NULL;
ALTER TABLE MINI_ERP.CUSTOMER_ORDER CHANGE TEL TEL varchar(50);
ALTER TABLE MINI_ERP.CUSTOMER_ORDER MODIFY COLUMN TEL varchar(50) NULL;


ALTER TABLE MINI_ERP.NEED_RES CHANGE RECEIVE_PERSON RECEIVE_PERSON varchar(50);
ALTER TABLE MINI_ERP.NEED_RES MODIFY COLUMN RECEIVE_PERSON varchar(50) NOT NULL;
ALTER TABLE MINI_ERP.NEED_RES CHANGE RECEIVE_TEL RECEIVE_TEL varchar(50);
ALTER TABLE MINI_ERP.NEED_RES MODIFY COLUMN RECEIVE_TEL varchar(50) NOT NULL;

INSERT INTO DG_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('erp.sale.receiveAddress','STRING','CITY','收货地址默认提取字段 CITY 城市 ADD 地址');
