INSERT INTO DG_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('erp.finance.useAdvance','BOOLEAN','false','使用预收货款');

-- oper

-- DEPOSIT_BACK

UPDATE MINI_ERP.ACCOUNT_OPER SET  ACCOUNTS_RECEIVABLE = ADVANCE_RECEIVABLE WHERE OPER_TYPE = 'DEPOSIT_BACK';

UPDATE MINI_ERP.ACCOUNT_OPER SET ADVANCE_RECEIVABLE = 0 WHERE OPER_TYPE = 'DEPOSIT_BACK';

UPDATE MINI_ERP.ACCOUNT_OPER SET ADVANCE_RECEIVABLE = 0 WHERE OPER_TYPE = 'ORDER_BACK';

UPDATE MINI_ERP.ACCOUNT_OPER SET ACCOUNTS_RECEIVABLE = ACCOUNTS_RECEIVABLE + ADVANCE_RECEIVABLE WHERE OPER_TYPE = 'CUSTOMER_SAVINGS';
UPDATE MINI_ERP.ACCOUNT_OPER SET ADVANCE_RECEIVABLE = 0 WHERE OPER_TYPE = 'CUSTOMER_SAVINGS';

DELETE FROM MINI_ERP.ACCOUNT_OPER WHERE OPER_TYPE = 'DEPOSIT_PAY';

UPDATE MINI_ERP.ACCOUNT_OPER SET ACCOUNTS_RECEIVABLE = ACCOUNTS_RECEIVABLE + ADVANCE_RECEIVABLE WHERE OPER_TYPE = 'ORDER_PAY';
UPDATE MINI_ERP.ACCOUNT_OPER SET ADVANCE_RECEIVABLE = 0 WHERE OPER_TYPE = 'ORDER_PAY';


UPDATE MINI_ERP.CUSTOMER SET ACCOUNT_MONEY = ACCOUNT_MONEY - ADVANCE_MONEY;

UPDATE MINI_ERP.CUSTOMER SET ADVANCE_MONEY = 0;



CREATE TABLE MINI_ERP.RES_SALE_REBATE
(
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  CUSTOMER_ORDER VARCHAR(32) NOT NULL COMMENT '订单',
  RES VARCHAR(32) NOT NULL COMMENT 'RES',
  RES_UNIT VARCHAR(32) NOT NULL COMMENT 'RES_UNIT',
  PRICE DECIMAL(19,4) NOT NULL COMMENT '单价',
  COUNT DECIMAL(19,4) NOT NULL COMMENT 'COUNT',
  MONEY DECIMAL(19,3) NOT NULL COMMENT '金额',
  REBATE_BASIC_COUNT DECIMAL(19,4) NOT NULL COMMENT '反点基数',
  REBATE_RATE_COUNT DECIMAL(19,4) NOT NULL COMMENT '返点数',
  REBATE_COUNT DECIMAL(19,4) NOT NULL COMMENT '返点数量',
  REBATE_MONEY DECIMAL(19,4) NOT NULL COMMENT '返点金额',
  MEMO VARCHAR(200) COMMENT '备注',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '物质销售返点' DEFAULT CHARACTER SET utf8;

ALTER TABLE MINI_ERP.RES_SALE_REBATE
ADD FOREIGN KEY (RES)
REFERENCES MINI_ERP.RES (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.RES_SALE_REBATE
ADD FOREIGN KEY (CUSTOMER_ORDER)
REFERENCES MINI_ERP.CUSTOMER_ORDER (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;