CREATE TABLE MINI_ERP.ORDER_REDUCE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	DESCRIPTION VARCHAR(200) COMMENT '描述',
	MONEY DECIMAL(19,4) NOT NULL COMMENT '金额',
	CUSTOMER_ORDER VARCHAR(32) NOT NULL COMMENT '订单',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ORDER_REDUCE' DEFAULT CHARACTER SET utf8;

ALTER TABLE MINI_ERP.ORDER_REDUCE
	ADD FOREIGN KEY (CUSTOMER_ORDER)
	REFERENCES MINI_ERP.CUSTOMER_ORDER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;