UPDATE DG_SYSTEM.BUSINESS_DEFINE SET NAME='客户退货' WHERE ID='erp.business.orderCancel';
UPDATE DG_SYSTEM.FUNCTION SET NAME='客户退货' WHERE ID='erp.sale.cancelAndbackRes';

INSERT INTO DG_SYSTEM.BUSINESS_DEFINE(ID, NAME, WF_NAME, START_PAGE, START_DATA_VALIDATOR, TASK_SERVICE, CATEGORY, MEMO, VERSION) VALUES('erp.business.orderMoneyBack','撤单退款','cancelOrderMoney',null ,'','','erp.sale','撤单退款',0);


ALTER TABLE MINI_ERP.ORDER_BACK DROP FOREIGN KEY ORDER_BACK_ibfk_2;
ALTER TABLE MINI_ERP.ORDER_BACK DROP CUSTOMER_ORDER;

ALTER TABLE MINI_ERP.ORDER_BACK DROP BACK_TYPE;

ALTER TABLE MINI_ERP.BACK_ITEM ADD DISPATCH VARCHAR(32) NULL;

ALTER TABLE MINI_ERP.BACK_ITEM
ADD FOREIGN KEY (DISPATCH)
REFERENCES MINI_ERP.BACK_DISPATCH (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.BACK_ITEM ADD STATUS VARCHAR(10) NOT NULL;
ALTER TABLE MINI_ERP.BACK_ITEM ADD TOTAL_MONEY DECIMAL(19, 3) NULL;
ALTER TABLE MINI_ERP.BACK_ITEM ADD REBATE DECIMAL(19, 4) NOT NULL;

ALTER TABLE MINI_ERP.PRODUCT_BACK_STORE_IN ADD STORE_OUT BIT(1) NOT NULL;

ALTER TABLE MINI_ERP.PRODUCT_BACK_STORE_IN RENAME TO MINI_ERP.BACK_DISPATCH;
-- ----------------------------------------------------

ALTER TABLE MINI_ERP.BACK_DISPATCH_ITEM DROP FOREIGN KEY BACK_DISPATCH_ITEM_ibfk_1;
ALTER TABLE MINI_ERP.BACK_DISPATCH_ITEM DROP FOREIGN KEY BACK_DISPATCH_ITEM_ibfk_2;
DROP TABLE MINI_ERP.BACK_DISPATCH_ITEM;