ALTER TABLE MINI_ERP.CUSTOMER_ORDER DROP INCLUDE_MIDDLE_MAN;
ALTER TABLE MINI_ERP.CUSTOMER_ORDER ADD RECEIVE_TYPE VARCHAR(20) NULL;

ALTER TABLE MINI_ERP.ORDER_REDUCE ADD TYPE VARCHAR(20) NOT NULL;
UPDATE MINI_ERP.ORDER_REDUCE SET TYPE ='OTHER_REDUCE';


ALTER TABLE MINI_ERP.CUSTOMER_ORDER ADD ACCOUNT_CHANGE BIT(1) NOT NULL;
UPDATE MINI_ERP.CUSTOMER_ORDER SET  ACCOUNT_CHANGE = b'1';

UPDATE MINI_ERP.CUSTOMER SET INIT_AD = 0 WHERE isnull(INIT_AD);
UPDATE MINI_ERP.CUSTOMER SET INIT_AC = 0 WHERE isnull(INIT_AC);
UPDATE MINI_ERP.CUSTOMER SET INIT_PAC = 0 WHERE isnull(INIT_PAC);
