ALTER TABLE MINI_ERP.CUSTOMER_ORDER DROP INCLUDE_MIDDLE_MAN;
ALTER TABLE MINI_ERP.CUSTOMER_ORDER ADD RECEIVE_TYPE VARCHAR(20) NULL;

ALTER TABLE MINI_ERP.ORDER_REDUCE ADD TYPE VARCHAR(20) NOT NULL;
UPDATE MINI_ERP.ORDER_REDUCE SET TYPE ='OTHER_REDUCE';


ALTER TABLE MINI_ERP.CUSTOMER_ORDER ADD ACCOUNT_CHANGE BIT(1) NOT NULL;
UPDATE MINI_ERP.CUSTOMER_ORDER SET  ACCOUNT_CHANGE = b'1';
