INSERT INTO DG_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('erp.finance.useAdvance','BOOLEAN','false','使用预收货款');

-- oper

-- DEPOSIT_BACK

UPDATE MINI_ERP.ACCOUNT_OPER SET  ACCOUNTS_RECEIVABLE = ADVANCE_RECEIVABLE WHERE OPER_TYPE = 'DEPOSIT_BACK';

UPDATE MINI_ERP.ACCOUNT_OPER SET ADVANCE_RECEIVABLE = 0 WHERE OPER_TYPE = 'DEPOSIT_BACK';

UPDATE MINI_ERP.ACCOUNT_OPER SET ADVANCE_RECEIVABLE = 0 WHERE OPER_TYPE = 'ORDER_BACK';