ALTER TABLE MINI_ERP.CUSTOMER ADD REBATE_PROGRAM VARCHAR(32) NULL;


CREATE TABLE MINI_ERP.SALER_PRICE
(
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  RES_UNIT VARCHAR(32) NOT NULL COMMENT 'RES_UNIT',
  RES VARCHAR(32) NOT NULL COMMENT 'RES',
  PRICE DECIMAL(19,3) NOT NULL COMMENT 'PRICE',
  MIDDLE_MAN VARCHAR(32) NOT NULL COMMENT 'MIDDLE_MAN',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '销售员价格' DEFAULT CHARACTER SET utf8;


CREATE TABLE MINI_ERP.SALER_STORE_RES_PRICE
(
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  RES_PRICE VARCHAR(32) NOT NULL COMMENT 'RES_PRICE',
  STORE_RES VARCHAR(32) NOT NULL COMMENT 'STORE_RES',
  RES_UNIT VARCHAR(32) NOT NULL COMMENT 'RES_UNIT',
  PRICE DECIMAL(19,3) NOT NULL COMMENT 'PRICE',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '物资底价' DEFAULT CHARACTER SET utf8;


ALTER TABLE MINI_ERP.CUSTOMER
ADD FOREIGN KEY (REBATE_PROGRAM)
REFERENCES MINI_ERP.REBATE_PROGRAM (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.SALER_PRICE
ADD FOREIGN KEY (RES)
REFERENCES MINI_ERP.RES (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.SALER_STORE_RES_PRICE
ADD FOREIGN KEY (RES_UNIT)
REFERENCES MINI_ERP.RES_UNIT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.SALER_PRICE
ADD FOREIGN KEY (MIDDLE_MAN)
REFERENCES MINI_ERP.MIDDLE_MAN (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


ALTER TABLE MINI_ERP.SALER_PRICE
ADD FOREIGN KEY (RES)
REFERENCES MINI_ERP.RES (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.SALER_PRICE
ADD FOREIGN KEY (RES_UNIT)
REFERENCES MINI_ERP.RES_UNIT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;



ALTER TABLE MINI_ERP.SALER_STORE_RES_PRICE
ADD FOREIGN KEY (RES_PRICE)
REFERENCES MINI_ERP.SALER_PRICE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.SALER_STORE_RES_PRICE
ADD FOREIGN KEY (STORE_RES)
REFERENCES MINI_ERP.STORE_RES (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


ALTER TABLE MINI_ERP.SALER_STORE_RES_PRICE
ADD FOREIGN KEY (RES_UNIT)
REFERENCES MINI_ERP.RES_UNIT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

UPDATE DG_SYSTEM.FUNCTION SET LOCATION='/func/erp/sale/mgr/MiddleManMgr.seam' WHERE ID ='erp.saler.middleManMgr';
DELETE FROM DG_SYSTEM.ROLE_FUNCTION WHERE  ROL_ID = 'erp.sale.saler'  AND  FUN_ID = 'erp.saler.middleManMgr';

DELETE FROM DG_SYSTEM.ROLE_FUNCTION WHERE FUN_ID = 'erp.sale.orderRebateCalc';
DELETE FROM DG_SYSTEM.FUNCTION WHERE ID ='erp.sale.orderRebateCalc';

