INSERT INTO DG_SYSTEM.FUNCTION (ID, NAME, CATEGORY, ICON, LOCATION, BANNER, PRIORITY, MEMO)
VALUES ('erp.total.procedureSaleChart', '产品销售情况', 'erp.total', '', '/func/erp/total/ProcedureSaleChart.seam', '', '130', '');


INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.sale.saler', 'erp.total.procedureSaleChart');


INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.sale.manager', 'erp.total.procedureSaleChart');


ALTER TABLE MINI_ERP.ORDER_ITEM ADD SALE_COUNT DECIMAL(19,4) NULL;


ALTER TABLE MINI_ERP.BACK_ITEM ADD SALE_COUNT DECIMAL(19,4) NULL;

UPDATE MINI_ERP.ORDER_ITEM SET SALE_COUNT = NEED_COUNT;

USE MINI_ERP;

UPDATE MINI_ERP.BACK_ITEM left join STORE_RES on STORE_RES.ID = BACK_ITEM.STORE_RES
  LEFT JOIN RES_UNIT on RES_UNIT.ID = BACK_ITEM.MONEY_UNIT LEFT JOIN UNIT_GROUP on UNIT_GROUP.ID = RES_UNIT.UNIT_GROUP
SET SALE_COUNT = COUNT * STORE_RES.FLOAT_CONVERSION_RATE  WHERE UNIT_GROUP.TYPE = 'FLOAT_CONVERT' and RES_UNIT.CONVERSION_RATE <> 1;


UPDATE MINI_ERP.BACK_ITEM
  LEFT JOIN RES_UNIT on RES_UNIT.ID = BACK_ITEM.MONEY_UNIT LEFT JOIN UNIT_GROUP on UNIT_GROUP.ID = RES_UNIT.UNIT_GROUP
SET SALE_COUNT = COUNT  WHERE UNIT_GROUP.TYPE <> 'FLOAT_CONVERT'





