DELETE FROM MINI_ERP.ACCOUNT_OPER WHERE OPER_TYPE='ORDER_PAY' and 
                                   ADVANCE_RECEIVABLE = 0 and ACCOUNTS_RECEIVABLE = 0 and PROXY_ACCOUNTS_RECEIVABLE = 0;




ALTER TABLE MINI_ERP.CUSTOMER_ORDER DROP RECEIVE_MONEY;

ALTER TABLE MINI_ERP.CUSTOMER_ORDER DROP MONEY_COMPLETE;

ALTER TABLE MINI_ERP.ORDER_BACK DROP MONEY_COMPLETE;


CREATE TABLE MINI_ERP.MONEY_SAVE
(
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  PAY_TYPE VARCHAR(32) NOT NULL COMMENT '支付方式',
  REMIT_FEE DECIMAL(19,3) NOT NULL COMMENT '汇款手续费',
  USE_CHECK BIT(1) NOT NULL COMMENT '支票',
  CHECK_NUMBER VARCHAR(50) COMMENT '支票号',
  NUMBER VARCHAR(100) NULL COMMENT '帐号',
  PROXY VARCHAR(32) NULL COMMENT 'PROXY',
  MONEY DECIMAL(19,3) NOT NULL COMMENT 'MONEY',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'MONEY_SAVE' DEFAULT CHARACTER SET utf8;


ALTER TABLE MINI_ERP.MONEY_SAVE
ADD FOREIGN KEY (PROXY)
REFERENCES MINI_ERP.TRANS_CORP (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.MONEY_SAVE
ADD FOREIGN KEY (NUMBER)
REFERENCES MINI_ERP.BANK_ACCOUNT (NUMBER)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


ALTER TABLE MINI_ERP.ACCOUNT_OPER ADD SAVEING VARCHAR(32) NULL;

ALTER TABLE MINI_ERP.ACCOUNT_OPER
ADD FOREIGN KEY (SAVEING)
REFERENCES MINI_ERP.MONEY_SAVE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

-- ORDER_SAVINGS -> proxy customer
-- PRE_DEPOSIT remove
-- ORDER_FREE -> MONEY_FREE

-- move

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP FOREIGN KEY ACCOUNT_OPER_ibfk_5;
ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP BANK_ACCOUNT;

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP FOREIGN KEY ACCOUNT_OPER_ibfk_6;
ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP CUSTOMER_ORDER;

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP FOREIGN KEY ACCOUNT_OPER_ibfk_4;
ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP ORDER_BACK;

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP REMIT_FEE;

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP PAY_TYPE;

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP CHECK_NUMBER;

ALTER TABLE MINI_ERP.ACCOUNT_OPER DROP USE_CHECK;



ALTER TABLE MINI_ERP.PREPARE_PAY DROP FOREIGN KEY PREPARE_PAY_ibfk_1;
DROP TABLE MINI_ERP.PREPARE_PAY;

ALTER TABLE MINI_ERP.BACK_PREPARE_MONEY DROP FOREIGN KEY BACK_PREPARE_MONEY_ibfk_1;
DROP TABLE MINI_ERP.BACK_PREPARE_MONEY;





