ALTER TABLE DG_SYSTEM.BUSINESS_TASK DROP FOREIGN KEY BUSINESS_TASK_ibfk_1;
ALTER TABLE DG_SYSTEM.BUSINESS_TASK DROP FOREIGN KEY BUSINESS_TASK_ibfk_2;
DROP TABLE DG_SYSTEM.BUSINESS_TASK;


ALTER TABLE DG_SYSTEM.BUSINESS_INSTANCE DROP FOREIGN KEY BUSINESS_INSTANCE_ibfk_1;
ALTER TABLE DG_SYSTEM.BUSINESS_INSTANCE DROP FOREIGN KEY BUSINESS_INSTANCE_ibfk_2;
DROP TABLE DG_SYSTEM.BUSINESS_INSTANCE;


ALTER TABLE MINI_ERP.ACCOUNT_OPER MODIFY COLUMN PAY_TYPE VARCHAR(32) NULL;

ALTER TABLE MINI_ERP.ACCOUNT_OPER MODIFY COLUMN REMIT_FEE DECIMAL(19,3) NULL;


