

ALTER TABLE MINI_ERP.CUSTOMER_ORDER ADD RES_MONEY DECIMAL(19,3) NOT NULL;

ALTER TABLE MINI_ERP.ORDER_ITEM ADD DISPATCH VARCHAR(32) NULL;

ALTER TABLE MINI_ERP.ORDER_ITEM
	ADD FOREIGN KEY (DISPATCH)
	REFERENCES MINI_ERP.DISPATCH (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.ORDER_ITEM ADD	STOCK_CHANGE_ITEM VARCHAR(32) NULL;

ALTER TABLE MINI_ERP.ORDER_ITEM
	ADD FOREIGN KEY (STOCK_CHANGE_ITEM)
	REFERENCES MINI_ERP.STOCK_CHANGE_ITEM (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.ORDER_ITEM ADD	STATUS VARCHAR(10) NOT NULL;

ALTER TABLE MINI_ERP.ORDER_ITEM ADD	OVERLAY_OUT BIT(1) NOT NULL;
ALTER TABLE MINI_ERP.ORDER_ITEM ADD	NEED_CONVERSION_RATE DECIMAL(19,10) NOT NULL;
ALTER TABLE MINI_ERP.ORDER_ITEM ADD	TOTAL_MONEY DECIMAL(19,3) NULL;





-- if count = 0

-- recreate
ALTER TABLE MINI_ERP.OVERLY_OUT RENAME TO MINI_ERP.OWE_OUT;
ALTER TABLE MINI_ERP.OWE_OUT ADD	NEED_CONVERSION_RATE DECIMAL(19,10) NOT NULL;






-- remove despatchItem

DROP TABLE MINI_ERP.DISPATCH_ITEM;

-- add OrderItem totalPrice  needtotalPrice  remove rebate   money rebate nullable


-- add CustomerOrder add RES_MONEY