UPDATE MINI_ERP.CUSTOMER SET ADVANCE_MONEY = 224955, ACCOUNT_MONEY = 72150 WHERE ID = '000013';  -- 王言雪

UPDATE MINI_ERP.CUSTOMER SET ADVANCE_MONEY = 3440, ACCOUNT_MONEY = 5400 WHERE ID = '000101'; -- 王超
UPDATE MINI_ERP.CUSTOMER SET ADVANCE_MONEY = 1459 WHERE ID = '000083'; -- 邵生业

UPDATE MINI_ERP.ACCOUNT_OPER SET ACCOUNTS_RECEIVABLE = 0 ,ADVANCE_RECEIVABLE = 20544 where ID='ff808081459480ca01459d38e7b001ba';

UPDATE MINI_ERP.ACCOUNT_OPER SET ACCOUNTS_RECEIVABLE = 0 ,ADVANCE_RECEIVABLE = 168000 where ID='ff80808145b3503d0145bfa4032200a6';

UPDATE MINI_ERP.ACCOUNT_OPER SET ACCOUNTS_RECEIVABLE = 0 ,ADVANCE_RECEIVABLE = 20394 where ID='ff80808145b3503d0145bfcd1fe800b5';


UPDATE DG_SYSTEM.SYSTEM_PARAM SET VALUE ='%s 发货' where ID = 'erp.ADF.rm.ORDER_PAY';
UPDATE DG_SYSTEM.SYSTEM_PARAM SET VALUE = '%s 发货' where ID = 'erp.ADF.ad.ORDER_PAY';


CREATE TABLE MINI_ERP.CERTIFICATE_ITEM
(
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  DESCRIPTION VARCHAR(200) COMMENT '描述',
  ACCOUNT_CODE VARCHAR(50) NOT NULL COMMENT '科目代码',
  DEBIT_MONEY DECIMAL(19,4) NOT NULL COMMENT '借方金额',
  CREDIT_MONEY DECIMAL(19,4) NOT NULL COMMENT '贷方金额',
  CERTIFICATE VARCHAR(32) NOT NULL COMMENT 'CERTIFICATE',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'CERTIFICATE_ITEM' DEFAULT CHARACTER SET utf8;

ALTER TABLE MINI_ERP.CERTIFICATE_ITEM
ADD FOREIGN KEY (CERTIFICATE)
REFERENCES MINI_ERP.SALE_PREPARED (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


INSERT INTO DG_SYSTEM.FUNCTION (ID, NAME, CATEGORY, ICON, LOCATION, BANNER, PRIORITY, MEMO) VALUES ('finance.account','结账','finance.config','','/func/erp/finance/accountancy/Accounting.seam','','4','');

INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.finance.accountancy', 'finance.account');

ALTER TABLE MINI_ERP.ORDER_BACK ADD COMPLETE_DATE timestamp NULL;


update MINI_ERP.ORDER_BACK SET COMPLETE_DATE = (SELECT MAX(OPER_DATE) from ACCOUNT_OPER WHERE ORDER_BACK=ORDER_BACK.ID) WHERE ORDER_BACK.MONEY_COMPLETE =b'1';


ALTER TABLE MINI_ERP.ORDER_BACK ADD COFIRMED bit NOT NULL;

UPDATE MINI_ERP.ORDER_BACK SET COFIRMED = b'1';

