ALTER TABLE MINI_ERP.CUSTOMER ADD CITY VARCHAR(100) NOT NULL;

UPDATE MINI_ERP.CUSTOMER  LEFT JOIN DG_SYSTEM.CITY p on p.PID  = CUSTOMER.PROVINCE_CODE
SET CUSTOMER.CITY = p.NAME ;


UPDATE MINI_ERP.CUSTOMER  LEFT JOIN DG_SYSTEM.CITY p on p.PID  = CUSTOMER.PROVINCE_CODE
SET CUSTOMER.PROVINCE_CODE = p.FID;

UPDATE DG_SYSTEM.FUNCTION SET NAME = '客户货款往来' WHERE ID = 'erp.search.customerMoneyReport';

UPDATE DG_SYSTEM.FUNCTION SET NAME = '客户货品往来明细', LOCATION='/func/erp/sale/CustomerResDetails.seam' WHERE ID = 'erp.search.customerShip';

UPDATE DG_SYSTEM.FUNCTION SET NAME = '货品往来分组汇总', LOCATION='/func/erp/sale/CustomerResTotal.seam' WHERE ID = 'erp.search.sallInOutDayReoper';

ALTER TABLE MINI_ERP.DISPATCH_ITEM DROP FOREIGN KEY DISPATCH_ITEM_ibfk_1;
ALTER TABLE MINI_ERP.DISPATCH_ITEM DROP FOREIGN KEY DISPATCH_ITEM_ibfk_2;
DROP TABLE MINI_ERP.DISPATCH_ITEM;