ALTER TABLE MINI_ERP.ORDER_ITEM ADD NEED_COUNT DECIMAL(19,4) NULL;


UPDATE  MINI_ERP.ORDER_ITEM left join STORE_RES on STORE_RES.ID = ORDER_ITEM.STORE_RES
SET NEED_COUNT =ORDER_ITEM.COUNT * ORDER_ITEM.NEED_COUNT


