

CREATE TABLE MINI_ERP.QUOTED_PRICE
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	CREATE_DATE TIMESTAMP NOT NULL COMMENT '报价日期',
	CREATE_EMP VARCHAR(32) NOT NULL COMMENT 'CREATE_EMP',
	CUSTOMER VARCHAR(32) NOT NULL COMMENT 'CUSTOMER',
	MEMO VARCHAR(200) COMMENT '备注',
	TYPE VARCHAR(32) NOT NULL COMMENT 'TYPE',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'QUOTED_PRICE' DEFAULT CHARACTER SET utf8;


CREATE TABLE MINI_ERP.PRICE_ITEM
(
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  QUOTED VARCHAR(32) NOT NULL COMMENT 'QUOTED',
  STORE_RES VARCHAR(32) NOT NULL COMMENT 'STORE_RES',
  COUNT DECIMAL(19,4) NOT NULL COMMENT 'COUNT',
  MEMO VARCHAR(200) COMMENT '备注',
  MONEY_UNIT VARCHAR(32) NOT NULL COMMENT 'MONEY_UNIT',
  MONEY DECIMAL(19,3) NOT NULL COMMENT '单价',
  PRIMARY KEY (ID),
  CONSTRAINT UNIQUE_STORERES_QUOTED UNIQUE (QUOTED, STORE_RES)
) ENGINE = InnoDB COMMENT = 'PRICE_ITEM' DEFAULT CHARACTER SET utf8;


ALTER TABLE MINI_ERP.PRICE_ITEM
	ADD FOREIGN KEY (MONEY_UNIT)
	REFERENCES MINI_ERP.RES_UNIT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.PRICE_ITEM
	ADD FOREIGN KEY (STORE_RES)
	REFERENCES MINI_ERP.STORE_RES (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MINI_ERP.QUOTED_PRICE
	ADD FOREIGN KEY (CUSTOMER)
	REFERENCES MINI_ERP.CUSTOMER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MINI_ERP.PRICE_ITEM
	ADD FOREIGN KEY (QUOTED)
	REFERENCES MINI_ERP.QUOTED_PRICE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


INSERT INTO DG_SYSTEM.FUNCTION (ID, NAME, CATEGORY, ICON, LOCATION, BANNER, PRIORITY, MEMO) VALUES ('erp.sale.quotedPrice','客户报价','erp.sale.mgr','','/func/erp/sale/QuotedPrice.seam','','3','');
INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.sale.saler', 'erp.sale.quotedPrice');
INSERT INTO DG_SYSTEM.ROLE_FUNCTION (ROL_ID, FUN_ID) VALUES ('erp.sale.manager', 'erp.sale.quotedPrice');


INSERT INTO DG_SYSTEM.WORD_CATEGORY(ID, NAME, MEMO, SYSTEM) VALUES ('erp.quotType','报价类型','',b'1');

INSERT INTO DG_SYSTEM.WORD(ID, _KEY, _VALUE, CATEGORY, DESCRIPTION, PRIORITY, ENABLE) VALUES ('erp.quotType.first','first','客户询价','erp.quotType','',1, b'1');
INSERT INTO DG_SYSTEM.WORD(ID, _KEY, _VALUE, CATEGORY, DESCRIPTION, PRIORITY, ENABLE) VALUES ('erp.quotType.prepare','prepare','预订单','erp.quotType','',2, b'1');
INSERT INTO DG_SYSTEM.WORD(ID, _KEY, _VALUE, CATEGORY, DESCRIPTION, PRIORITY, ENABLE) VALUES ('erp.quotType.other','othre','其它','erp.quotType','',20, b'1');
