ALTER TABLE MINI_ERP.OVERLY_OUT ADD IS_ADD BIT(1) NOT NULL;

ALTER TABLE MINI_ERP.NEED_RES ADD STATUS VARCHAR(32) NOT NULL;

ALTER TABLE MINI_ERP.NEED_RES DROP DISPATCHED;

ALTER TABLE MINI_ERP.DISPATCH ADD STORE_OUT BIT(1) NOT NULL;

ALTER TABLE MINI_ERP.DISPATCH DROP STATE;

ALTER TABLE MINI_ERP.ORDER_ITEM DROP FOREIGN KEY ORDER_ITEM_ibfk_6;
ALTER TABLE MINI_ERP.ORDER_ITEM DROP OVERLY_OUT;

ALTER TABLE MINI_ERP.NEED_RES DROP PROXY_FARE;
