ALTER TABLE MINI_ERP.OVERLY_OUT ADD IS_ADD BIT(1) NOT NULL;

UPDATE MINI_ERP.OVERLY_OUT SET IS_ADD = b'1';

ALTER TABLE MINI_ERP.NEED_RES ADD STATUS VARCHAR(32) NOT NULL;

UPDATE MINI_ERP.NEED_RES SET STATUS = 'CREATED' WHERE DISPATCHED = b'0';
UPDATE MINI_ERP.NEED_RES SET STATUS = 'DISPATCHED' WHERE DISPATCHED = b'1';

ALTER TABLE MINI_ERP.NEED_RES DROP DISPATCHED;

ALTER TABLE MINI_ERP.DISPATCH ADD STORE_OUT BIT(1) NOT NULL;

UPDATE MINI_ERP.DISPATCH SET STORE_OUT = b'1';
UPDATE MINI_ERP.DISPATCH SET STORE_OUT = b'0' WHERE STATE = 'DISPATCH_COMPLETE';

ALTER TABLE MINI_ERP.DISPATCH DROP STATE;

ALTER TABLE MINI_ERP.ORDER_ITEM DROP FOREIGN KEY ORDER_ITEM_ibfk_6;
ALTER TABLE MINI_ERP.ORDER_ITEM DROP OVERLY_OUT;

ALTER TABLE MINI_ERP.NEED_RES DROP PROXY_FARE;
